/* ════════════════════════════════════════════════════════════════════
   CACCO — Language / i18n context
   Supports: en (English) · es (Spanish)
   ════════════════════════════════════════════════════════════════════ */
import React, { createContext, useContext, useState } from 'react';

const DICT = {
  /* ──────────────────────── ENGLISH ─────────────────────────────── */
  en: {
    /* Navigation */
    nav: {
      group: {
        Command: 'Command', Operations: 'Operations', Intelligence: 'Intelligence',
        Facility: 'Facility', Governance: 'Governance',
      },
      item: {
        commandCenter: 'Command Center',
        securityOps: 'Security Operations',
        surveillance: 'Surveillance Center',
        incidents: 'Incident Management',
        inmateIntel: 'Inmate Intelligence',
        aiAnalytics: 'AI Analytics',
        staffOps: 'Staff Operations',
        rehab: 'Rehabilitation Programs',
        twin: 'Digital Twin',
        reports: 'Reports & Compliance',
        admin: 'System Administration',
      },
    },
    /* Layout shell */
    layout: {
      platform: 'COMMAND PLATFORM',
      logout: 'Logout / Lock Session',
      search: 'Search platform\u2026  Ctrl+K',
      onDuty: 'ON DUTY',
      advisory: 'S!aP Advisory',
    },
    /* ── Command Center ── */
    cc: {
      title: 'Command Center',
      subtitle: 'Real-time situational awareness · all zones · all operations',
      strategicIndicators: 'Strategic Indicators',
      opStatusTitle: 'Operational Status — Facility Zones',
      opStatusSub: 'Live occupancy, incident and posture readout per zone',
      liveAlerts: 'Live Alert Stream',
      aiAdvisor: 'AI Operations Advisor',
      aiAdvisorSub: 'Prison intelligence recommendations',
      threatIntel: 'Threat Intelligence Feed',
      threatIntelSub: 'Crime · contraband · behavioral · perimeter',
      responseTitle: 'Response Team Readiness',
      responseSub: 'Real-time team status · deployment capability',
    },
    /* ── Security Operations ── */
    sec: {
      title: 'Security Operations',
      subtitle: 'Facility posture · response coordination · perimeter integrity',
      activeAlerts: 'Active Alerts',
      deployed: 'Teams Deployed',
      lockdownZones: 'Lockdown Zones',
      perimeter: 'Perimeter Sectors',
      postureTitle: 'Security Posture Control',
      postureSub: 'Set facility-wide alert level',
      zoneMatrix: 'Zone Security Matrix',
      responseTitle: 'Response Teams',
      responseSub: 'Tactical readiness',
      perimeterPanel: 'Perimeter Integrity',
      alertsPanel: 'Active Security Alerts',
      initLockdown: 'INITIATE LOCKDOWN',
      deploy: 'DEPLOY',
      recall: 'RECALL TO STANDBY',
      liveEvents: 'No active alerts — facility nominal.',
    },
    /* ── Surveillance Center ── */
    surv: {
      title: 'Surveillance Center',
      subtitle: 'CCTV grid · AI video analytics · camera health monitoring',
      cameraGrid: 'Camera Grid',
      cameraHealth: 'Camera Health',
      aiActivity: 'AI Detection Activity',
      onlineCameras: 'Online Cameras',
      offlineCameras: 'Offline Cameras',
      flaggedCameras: 'AI Flagged',
      totalCameras: 'Total Cameras',
    },
    /* ── Incident Management ── */
    inc: {
      title: 'Incident Management',
      subtitle: 'Full lifecycle case management from report to closure',
      boardTitle: 'Incident Lifecycle Board',
      boardSub: 'Drag-free kanban — click a card for the full case file',
      summaryTitle: 'Board Summary',
      totalCases: 'Total Cases',
      criticalCases: 'Critical Severity',
      casualtiesReported: 'Casualties Reported',
      oldestOpen: 'Oldest Open Case',
      logTitle: 'Incident Log',
      distTitle: 'Incident Type Distribution',
      bySeverity: 'By Severity',
      thId: 'ID', thType: 'Type', thSev: 'Severity', thZone: 'Zone',
      thStage: 'Stage', thCmd: 'Commander', thRep: 'Reported',
    },
    /* ── Inmate Intelligence ── */
    intel: {
      title: 'Inmate Intelligence',
      subtitle: 'Population profiling · association analysis · behavioral monitoring',
      riskStrat: 'Risk Stratification',
      crimeDistrib: 'Crime Category Distribution',
      watchlist: 'Critical Watchlist',
      popSummary: 'Population Summary',
      assocGraph: 'Association Graph',
      profileDossier: 'Subject Dossier',
      intFlags: 'Intelligence Flags',
      associates: 'Known Associates',
      thId: 'ID', thName: 'Name', thCrime: 'Crime Type', thCustody: 'Custody Level',
      thRisk: 'Risk', thThreat: 'Threat Score', thZone: 'Zone', thStatus: 'Status',
      thNat: 'Nationality', thFlags: 'Flags',
    },
    /* ── AI Analytics ── */
    ai: {
      title: 'AI Analytics',
      subtitle: 'Predictive threat modelling · behavioral pattern analysis · intelligence fusion',
      forecastTitle: 'Threat Forecast',
      riskStrat: 'Population Risk Stratification',
      modelsTitle: 'Active AI Models',
      modelsSub: 'Inference pipeline status',
      recsTitle: 'Priority Recommendations',
      recsSub: 'AI-generated operational guidance',
      crimeProfile: 'Crime Category Threat Profile',
      crimeProfileSub: 'Avg AI threat score per crime category',
      topSignals: 'Top Intelligence Signals',
      topSignalsSub: 'Highest-confidence threat indicators',
    },
    /* ── Staff Operations ── */
    staff: {
      title: 'Staff Operations',
      subtitle: 'Personnel roster · shift deployment · clearance management',
      totalPersonnel: 'Total Personnel',
      onDuty: 'On Duty',
      inResponse: 'In Active Response',
      offDuty: 'Off Duty / Leave',
      roster: 'Personnel Roster',
      shiftReadiness: 'Shift Readiness',
      roleDist: 'Role Distribution',
      zoneDeploy: 'Zone Deployment',
      thBadge: 'Badge', thName: 'Name', thRole: 'Role', thShift: 'Shift',
      thStatus: 'Status', thZone: 'Zone', thClearance: 'Clearance',
      subAll: 'all shifts combined',
      subForce: 'of force',
      subIncident: 'incident deployment',
      subUnavail: 'unavailable',
    },
    /* ── Rehabilitation Programs ── */
    rehab: {
      title: 'Rehabilitation Programs',
      subtitle: 'Education · vocational training · psychological support · reintegration',
      programsActive: 'Programs Active',
      totalEnrolled: 'Total Enrolled',
      avgCompletion: 'Avg Completion Rate',
      totalCapacity: 'Total Capacity',
      activePrograms: 'Active Programs',
      categoryOverview: 'Category Overview',
      compliance: 'Compliance Indicators',
      programRegister: 'Program Register',
      thId: 'ID', thProgram: 'Program', thCategory: 'Category', thFacilitator: 'Facilitator',
      thEnrolled: 'Enrolled', thCapacity: 'Capacity', thUtil: 'Utilization', thCompletion: 'Completion',
      subAllCat: 'all categories',
      subPop: 'of population',
      subAcross: 'across all programs',
      subUtil: 'utilization',
      enrolled: 'ENROLLED',
      avgComp: 'AVG COMPLETION',
    },
    /* ── Digital Twin ── */
    twin: {
      title: 'Digital Twin',
      subtitle: 'Real-time schematic model of CACCO physical plant',
      schematic: 'Facility Schematic — Sector Overview',
      schematicSub: '3D campus model · drag to orbit, scroll to zoom',
      zoneDetail: 'Zone Detail',
      layers: 'Map Layers',
    },
    /* ── Reports & Compliance ── */
    rpt: {
      title: 'Reports & Compliance',
      subtitle: 'Statutory reporting · audit trail · Ministry of Justice and Peace submissions',
      scheduleTitle: 'Report Schedule',
      auditTitle: 'Audit Log',
      statsTitle: 'Compliance Statistics',
      thId: 'ID', thReport: 'Report', thCategory: 'Category', thFreq: 'Frequency',
      thLast: 'Last Generated', thNext: 'Next Due', thStatus: 'Status', thRecipient: 'Recipient',
      thTime: 'Time', thAction: 'Action', thUser: 'User', thRef: 'Reference',
      exportBtn: 'EXPORT PDF',
    },
    /* ── System Admin ── */
    admin: {
      title: 'System Administration',
      subtitle: 'Service health · access control · integrations · security configuration',
      servicesTitle: 'Service Health',
      accessTitle: 'Access Control & Sessions',
      integrationsTitle: 'External Integrations',
      servicesOnline: 'Services Online',
      avgLatency: 'Avg Latency',
      sessions: 'Active Sessions',
      mfaAlert: 'MFA Non-Compliant',
      thId: 'ID', thService: 'Service', thStatus: 'Status', thLatency: 'Latency',
      thUptime: 'Uptime', thCategory: 'Category',
      thUser: 'User', thRole: 'Role', thClearance: 'Clearance',
      thLastLogin: 'Last Login', thMFA: 'MFA',
    },
    /* Common */
    common: {
      viewDetails: 'VIEW DETAILS',
      execute: 'EXECUTE RECOMMENDATION',
      close: 'Close',
      ack: 'ACK',
      search: 'Search',
      active: 'ACTIVE',
      officers: 'officers',
      ofPop: '% of pop.',
      modelConf: 'Model Confidence',
      noAlerts: 'No active alerts.',
      noPrograms: 'No programs in this category.',
      live: 'LIVE',
      occupancy: 'Occupancy',
      incidents: 'Incidents',
      personnel: 'Personnel',
      risk: 'Risk',
      zone: 'Zone',
      status: 'Status',
      resumeStream: 'Resume stream',
      pauseStream: 'Pause stream',
      high: 'HIGH',
      rdy: 'RDY',
      opr: 'OPR',
      sallyPort1: 'Sally Port 1',
      sallyPort2: 'Sally Port 2',
      vehicleGate: 'Vehicle Gate',
      droneOverwatch: 'Drone Overwatch',
      secured: 'SECURED',
      staged: 'STAGED',
      activeStatus: 'ACTIVE',
      cobra: 'COBRA',
      criticalRecs: 'CRITICAL RECS',
      highPriorityRecs: 'High-Priority Recs',
      requireImmediateReview: 'require immediate review',
      highestSeverity: 'highest severity',
      highRiskInmates: 'High-Risk Inmates',
      riskGreaterThanHigh: 'risk ≥ High',
    },
  },

  /* ──────────────────────── SPANISH ─────────────────────────────── */
  es: {
    nav: {
      group: {
        Command: 'Comando', Operations: 'Operaciones', Intelligence: 'Inteligencia',
        Facility: 'Instalaciones', Governance: 'Gobernanza',
      },
      item: {
        commandCenter: 'Centro de Comando',
        securityOps: 'Operaciones de Seguridad',
        surveillance: 'Centro de Vigilancia',
        incidents: 'Gestión de Incidentes',
        inmateIntel: 'Inteligencia de Reclusos',
        aiAnalytics: 'Análisis IA',
        staffOps: 'Operaciones de Personal',
        rehab: 'Programas de Rehabilitación',
        twin: 'Gemelo Digital',
        reports: 'Informes y Cumplimiento',
        admin: 'Administración del Sistema',
      },
    },
    layout: {
      platform: 'PLATAFORMA DE MANDO',
      logout: 'Cerrar Sesión',
      search: 'Buscar plataforma\u2026  Ctrl+K',
      onDuty: 'DE GUARDIA',
      advisory: 'S!aP Asesoría',
    },
    cc: {
      title: 'Centro de Comando',
      subtitle: 'Conciencia situacional en tiempo real · todas las zonas · todas las operaciones',
      strategicIndicators: 'Indicadores Estratégicos',
      opStatusTitle: 'Estado Operacional — Zonas del Centro',
      opStatusSub: 'Ocupación en vivo, incidentes y estado de postura por zona',
      liveAlerts: 'Flujo de Alertas en Vivo',
      aiAdvisor: 'Asesor de Operaciones IA',
      aiAdvisorSub: 'Recomendaciones de inteligencia penitenciaria',
      threatIntel: 'Inteligencia de Amenazas',
      threatIntelSub: 'Crimen · contrabando · conductual · perímetro',
      responseTitle: 'Preparación de Equipos de Respuesta',
      responseSub: 'Estado del equipo en tiempo real · capacidad de despliegue',
    },
    sec: {
      title: 'Operaciones de Seguridad',
      subtitle: 'Postura del centro · coordinación de respuesta · integridad del perímetro',
      activeAlerts: 'Alertas Activas',
      deployed: 'Equipos Desplegados',
      lockdownZones: 'Zonas en Bloqueo',
      perimeter: 'Sectores Perimetrales',
      postureTitle: 'Control de Postura de Seguridad',
      postureSub: 'Establecer nivel de alerta en todo el centro',
      zoneMatrix: 'Matriz de Seguridad por Zona',
      responseTitle: 'Equipos de Respuesta',
      responseSub: 'Disponibilidad táctica',
      perimeterPanel: 'Integridad del Perímetro',
      alertsPanel: 'Alertas de Seguridad Activas',
      initLockdown: 'INICIAR BLOQUEO',
      deploy: 'DESPLEGAR',
      recall: 'LLAMAR A POSICIÓN',
      liveEvents: 'Sin alertas activas — instalación nominal.',
    },
    surv: {
      title: 'Centro de Vigilancia',
      subtitle: 'Red CCTV · análisis de video IA · monitoreo de salud de cámaras',
      cameraGrid: 'Cuadrícula de Cámaras',
      cameraHealth: 'Estado de Cámaras',
      aiActivity: 'Actividad de Detección IA',
      onlineCameras: 'Cámaras en Línea',
      offlineCameras: 'Cámaras Desconectadas',
      flaggedCameras: 'Marcadas por IA',
      totalCameras: 'Total de Cámaras',
    },
    inc: {
      title: 'Gestión de Incidentes',
      subtitle: 'Gestión completa del ciclo de vida desde el reporte hasta el cierre',
      boardTitle: 'Tablero del Ciclo de Vida de Incidentes',
      boardSub: 'Kanban — haga clic en una tarjeta para ver el expediente completo',
      summaryTitle: 'Resumen del Tablero',
      totalCases: 'Casos Totales',
      criticalCases: 'Gravedad Crítica',
      casualtiesReported: 'Víctimas Reportadas',
      oldestOpen: 'Caso Abierto Más Antiguo',
      logTitle: 'Registro de Incidentes',
      distTitle: 'Distribución por Tipo de Incidente',
      bySeverity: 'Por Gravedad',
      thId: 'ID', thType: 'Tipo', thSev: 'Gravedad', thZone: 'Zona',
      thStage: 'Etapa', thCmd: 'Comandante', thRep: 'Reportado',
    },
    intel: {
      title: 'Inteligencia de Reclusos',
      subtitle: 'Perfiles de población · análisis de asociación · monitoreo conductual',
      riskStrat: 'Estratificación de Riesgo',
      crimeDistrib: 'Distribución por Categoría de Delito',
      watchlist: 'Lista de Vigilancia Crítica',
      popSummary: 'Resumen de Población',
      assocGraph: 'Gráfico de Asociación',
      profileDossier: 'Dossier del Sujeto',
      intFlags: 'Marcadores de Inteligencia',
      associates: 'Asociados Conocidos',
      thId: 'ID', thName: 'Nombre', thCrime: 'Tipo de Delito', thCustody: 'Nivel de Custodia',
      thRisk: 'Riesgo', thThreat: 'Puntuación de Amenaza', thZone: 'Zona', thStatus: 'Estado',
      thNat: 'Nacionalidad', thFlags: 'Marcadores',
    },
    ai: {
      title: 'Análisis IA',
      subtitle: 'Modelado predictivo de amenazas · análisis de patrones conductuales · fusión de inteligencia',
      forecastTitle: 'Pronóstico de Amenazas',
      riskStrat: 'Estratificación de Riesgo de Población',
      modelsTitle: 'Modelos IA Activos',
      modelsSub: 'Estado del canal de inferencia',
      recsTitle: 'Recomendaciones Prioritarias',
      recsSub: 'Guía operacional generada por IA',
      crimeProfile: 'Perfil de Amenazas por Categoría de Delito',
      crimeProfileSub: 'Puntuación promedio de amenaza IA por categoría de delito',
      topSignals: 'Principales Señales de Inteligencia',
      topSignalsSub: 'Indicadores de mayor confianza',
    },
    staff: {
      title: 'Operaciones de Personal',
      subtitle: 'Plantilla de personal · gestión de turnos · control de habilitación',
      totalPersonnel: 'Total de Personal',
      onDuty: 'De Guardia',
      inResponse: 'En Respuesta Activa',
      offDuty: 'Fuera de Servicio / Permiso',
      roster: 'Registro de Personal',
      shiftReadiness: 'Disponibilidad por Turno',
      roleDist: 'Distribución de Roles',
      zoneDeploy: 'Despliegue por Zona',
      thBadge: 'Placa', thName: 'Nombre', thRole: 'Cargo', thShift: 'Turno',
      thStatus: 'Estado', thZone: 'Zona', thClearance: 'Habilitación',
      subAll: 'todos los turnos combinados',
      subForce: 'de la fuerza',
      subIncident: 'despliegue de incidentes',
      subUnavail: 'no disponible',
    },
    rehab: {
      title: 'Programas de Rehabilitación',
      subtitle: 'Educación · formación vocacional · apoyo psicológico · reinserción',
      programsActive: 'Programas Activos',
      totalEnrolled: 'Total Matriculados',
      avgCompletion: 'Tasa Media de Completitud',
      totalCapacity: 'Capacidad Total',
      activePrograms: 'Programas Activos',
      categoryOverview: 'Resumen por Categoría',
      compliance: 'Indicadores de Cumplimiento',
      programRegister: 'Registro de Programas',
      thId: 'ID', thProgram: 'Programa', thCategory: 'Categoría', thFacilitator: 'Facilitador',
      thEnrolled: 'Matriculados', thCapacity: 'Capacidad', thUtil: 'Utilización', thCompletion: 'Completitud',
      subAllCat: 'todas las categorías',
      subPop: 'de la población',
      subAcross: 'en todos los programas',
      subUtil: 'utilización',
      enrolled: 'MATRICULADOS',
      avgComp: 'COMPLETITUD PROMEDIO',
    },
    twin: {
      title: 'Gemelo Digital',
      subtitle: 'Modelo esquemático en tiempo real de la planta física CACCO',
      schematic: 'Esquema del Centro — Vista de Sectores',
      schematicSub: 'Modelo 3D del campus · arrastre para orbitar, desplácese para acercar',
      zoneDetail: 'Detalle de Zona',
      layers: 'Capas del Mapa',
    },
    rpt: {
      title: 'Informes y Cumplimiento',
      subtitle: 'Informes estatutarios · registro de auditoría · presentaciones al Ministerio de Justicia y Paz',
      scheduleTitle: 'Calendario de Informes',
      auditTitle: 'Registro de Auditoría',
      statsTitle: 'Estadísticas de Cumplimiento',
      thId: 'ID', thReport: 'Informe', thCategory: 'Categoría', thFreq: 'Frecuencia',
      thLast: 'Última Generación', thNext: 'Próximo Vencimiento', thStatus: 'Estado', thRecipient: 'Destinatario',
      thTime: 'Hora', thAction: 'Acción', thUser: 'Usuario', thRef: 'Referencia',
      exportBtn: 'EXPORTAR PDF',
    },
    admin: {
      title: 'Administración del Sistema',
      subtitle: 'Salud de servicios · control de acceso · integraciones · configuración de seguridad',
      servicesTitle: 'Salud de Servicios',
      accessTitle: 'Control de Acceso y Sesiones',
      integrationsTitle: 'Integraciones Externas',
      servicesOnline: 'Servicios en Línea',
      avgLatency: 'Latencia Promedio',
      sessions: 'Sesiones Activas',
      mfaAlert: 'Sin Cumplimiento MFA',
      thId: 'ID', thService: 'Servicio', thStatus: 'Estado', thLatency: 'Latencia',
      thUptime: 'Disponibilidad', thCategory: 'Categoría',
      thUser: 'Usuario', thRole: 'Cargo', thClearance: 'Habilitación',
      thLastLogin: 'Último Acceso', thMFA: 'MFA',
    },
    common: {
      viewDetails: 'VER DETALLES',
      execute: 'EJECUTAR RECOMENDACIÓN',
      close: 'Cerrar',
      ack: 'ACK',
      search: 'Buscar',
      active: 'ACTIVO',
      officers: 'oficiales',
      ofPop: '% de pob.',
      modelConf: 'Confianza del Modelo',
      noAlerts: 'Sin alertas activas.',
      noPrograms: 'Sin programas en esta categoría.',
      live: 'EN VIVO',
      occupancy: 'Ocupación',
      incidents: 'Incidentes',
      personnel: 'Personal',
      risk: 'Riesgo',
      zone: 'Zona',
      status: 'Estado',
      resumeStream: 'Reanudar flujo',
      pauseStream: 'Pausar flujo',
      high: 'ALTO',
      rdy: 'PREP',
      opr: 'OPR',
      sallyPort1: 'Puerta Sally 1',
      sallyPort2: 'Puerta Sally 2',
      vehicleGate: 'Puerta de Vehículos',
      droneOverwatch: 'Vigilancia por Dron',
      secured: 'ASEGURADO',
      staged: 'ESCALONADO',
      activeStatus: 'ACTIVO',
      cobra: 'COBRA',
      criticalRecs: 'RECS CRÍTICAS',
      highPriorityRecs: 'Recs de Alta Prioridad',
      requireImmediateReview: 'requiere revisión inmediata',
      highestSeverity: 'gravedad máxima',
      highRiskInmates: 'Reclusos de Alto Riesgo',
      riskGreaterThanHigh: 'riesgo ≥ Alto',
    },
  },
};

/* ─── Context ───────────────────────────────────────────────────────── */
const LanguageCtx = createContext({ lang: 'en', toggleLang: () => {} });

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const toggleLang = () => setLang((l) => (l === 'en' ? 'es' : 'en'));
  return <LanguageCtx.Provider value={{ lang, toggleLang }}>{children}</LanguageCtx.Provider>;
}

export function useLanguage() {
  return useContext(LanguageCtx);
}

/* ─── Translation hook ──────────────────────────────────────────────── */
export function useT() {
  const { lang, toggleLang } = useContext(LanguageCtx);
  const dict = DICT[lang];

  /** Dot-notation lookup: t('cc.title') → string */
  const t = (path) => {
    const parts = path.split('.');
    let node = dict;
    for (const p of parts) {
      if (node == null) return path;
      node = node[p];
    }
    return node ?? path;
  };

  return { t, lang, toggleLang };
}
