/* ════════════════════════════════════════════════════════════════════
   CACCO — Language / i18n context
   Supports: en (English) · es (Spanish)
   ════════════════════════════════════════════════════════════════════ */
import React, { createContext, useContext, useState } from 'react';

const DICT = {
  /* ──────────────────────── ENGLISH ─────────────────────────────── */
  en: {
    /* Navigation */
    nav: {
      group: {
        Command: 'Command', Operations: 'Operations', Intelligence: 'Intelligence',
        Facility: 'Facility', Governance: 'Governance',
      },
      item: {
        commandCenter: 'Command Center',
        securityOps: 'Security Operations',
        surveillance: 'Surveillance Center',
        incidents: 'Incident Management',
        inmateIntel: 'Inmate Intelligence',
        aiAnalytics: 'AI Analytics',
        staffOps: 'Staff Operations',
        rehab: 'Rehabilitation Programs',
        twin: 'Digital Twin',
        reports: 'Reports & Compliance',
        admin: 'System Administration',
      },
    },
    /* Layout shell */
    layout: {
      platform: 'COMMAND PLATFORM',
      logout: 'Logout / Lock Session',
      search: 'Search platform…  Ctrl+K',
      onDuty: 'ON DUTY',
      advisory: 'S!aP Advisory',
      profileUser: 'Profile',
      profileNotifications: 'Notifications',
      profileSettings: 'Settings',
      profileOnline: 'Online',
      profileEngineer: 'Design Engineer',
      drawerIntelTitle: 'Threat Intelligence Feed',
      drawerIntelSubActive: 'active assessments',
      drawerIntelAlerts: 'Active Security Alerts',
      drawerIntelAssess: 'Intelligence Assessments',
      drawerAdvisory: 'S!aP Advisory',
      drawerAdvisorySubRecs: 'recommendations',
      footerRestricted: 'RESTRICTED',
      footerPlatform: 'CACCO Command Platform · Costa Rican Ministry of Justice and Peace',
      footerDataRefresh: 'DATA REFRESH',
      footerNominal: 'SYSTEMS NOMINAL',
      searchNoResults: 'No results for',
    },
    /* ── Command Center ── */
    cc: {
      title: 'Command Center',
      subtitle: 'Real-time situational awareness · all zones · all operations',
      strategicIndicators: 'Strategic Indicators',
      opStatusTitle: 'Operational Status — Facility Zones',
      opStatusSub: 'Live occupancy, incident and posture readout per zone',
      liveAlerts: 'Live Alert Stream',
      aiAdvisor: 'AI Operations Advisor',
      aiAdvisorSub: 'Prison intelligence recommendations',
      threatIntel: 'Threat Intelligence Feed',
      threatIntelSub: 'Crime · contraband · behavioral · perimeter',
      responseTitle: 'Response Team Readiness',
      responseSub: 'Real-time team status · deployment capability',
      facilityName: 'CENTRO DE ALTA CONTENCIÓN DEL CRIMEN ORGANIZADO',
      modalZoneActions: 'Zone Actions',
      modalZoneOccupancy: 'Occupancy',
      modalZoneRisk: 'Risk',
      modalActionLabel: 'Action to execute',
      modalPriorityLabel: 'Priority level',
      optLockdown: 'Order lockdown',
      optPatrol: 'Request additional patrol',
      optIncident: 'Log incident',
      optPersonnel: 'Assign additional personnel',
      optCritical: 'Critical',
      optHigh: 'High',
      optMedium: 'Medium',
      optLow: 'Low',
      executeAction: 'Execute action',
      toastAction: 'Action executed in',
      executeRec: 'Execute recommendation',
      recTeamLabel: 'Assigned team',
      recTimeline: 'Execution timeline',
      recOptImmediate: 'Immediate (< 15 min)',
      recOpt1h: 'Within 1 hour',
      recOpt4h: 'Within 4 hours',
      recOptShift: 'Next shift',
      recNotesLabel: 'Operator notes',
      recNotesPh: 'Enter additional observations...',
      ackTitle: 'Acknowledge alert',
      ackActionLabel: 'Action taken',
      ackOptDispatched: 'Team dispatched',
      ackOptMonitoring: 'Continuous monitoring',
      ackOptResolved: 'Resolved without intervention',
      ackOptEscalated: 'Escalated to command',
      ackOfficerLabel: 'Responsible officer',
      ackOfficerPh: 'Badge number or name',
      ackNotesLabel: 'Observations',
      ackNotesPh: 'Describe the action taken...',
      ackConfirm: 'Confirm receipt',
      personnel: 'personnel',
    },
    /* ── Security Operations ── */
    sec: {
      title: 'Security Operations',
      subtitle: 'Facility posture · response coordination · perimeter integrity',
      activeAlerts: 'Active Alerts',
      deployed: 'Teams Deployed',
      lockdownZones: 'Lockdown Zones',
      perimeter: 'Perimeter Sectors',
      postureTitle: 'Security Posture Control',
      postureSub: 'Set facility-wide alert level',
      zoneMatrix: 'Zone Security Matrix',
      responseTitle: 'Response Teams',
      responseSub: 'Tactical readiness',
      perimeterPanel: 'Perimeter Integrity',
      alertsPanel: 'Active Security Alerts',
      initLockdown: 'INITIATE LOCKDOWN',
      deploy: 'DEPLOY',
      recall: 'RECALL TO STANDBY',
      liveEvents: 'No active alerts — facility nominal.',
      postureDesc1: 'Routine operations. Standard patrols and movement schedules in effect.',
      postureDesc2: 'Increased vigilance. Enhanced patrols; non-essential movement restricted.',
      postureDesc3: 'High alert. Movement controlled; response teams staged; intel surge active.',
      postureDesc4: 'Critical incident. Full lockdown protocol; all teams deployed; external liaison engaged.',
      activeLabel: 'ACTIVE',
      subLiveEvents: 'live security events',
      subResponseReadiness: 'response readiness',
      subMovementHalted: 'movement halted',
      subSecureTotal: 'secure / total',
      sectorN7: 'North Line 7',
      sectorN8: 'North Line 8',
      sectorE1: 'East Gate',
      sectorE2: 'East Fence',
      sectorS4: 'South Yard',
      sectorS5: 'South Line',
      sectorW3: 'West Tower',
      sectorW6: 'West Fence',
      sectorStatusSecure: 'SECURE',
      sectorStatusWatch: 'WATCH',
      sectorStatusAlert: 'ALERT',
      lockdownSelectZone: 'Select zone to confine',
      lockdownZoneLabel: 'Zone to confine',
      lockdownTypeLabel: 'Lockdown type',
      lockdownFull: 'Full lockdown',
      lockdownPartial: 'Partial lockdown',
      lockdownPreventive: 'Preventive lockdown',
      lockdownDuration: 'Estimated duration',
      lockdownOpt30m: '30 minutes',
      lockdownOpt1h: '1 hour',
      lockdownOpt4h: '4 hours',
      lockdownOptIndefinite: 'Until further notice',
      lockdownReasonLabel: 'Reason for lockdown',
      lockdownReasonPh: 'Describe the reason for the lockdown order...',
      deployZoneLabel: 'Deployment zone',
      deployMissionLabel: 'Mission type',
      missionPatrol: 'Patrol',
      missionResponse: 'Incident response',
      missionLockdown: 'Lockdown support',
      missionEscort: 'Prisoner escort',
      deployNotesLabel: 'Special instructions',
      deployNotesPh: 'Enter additional instructions...',
      recallReasonLabel: 'Reason for return',
      recallMissionComplete: 'Mission completed',
      recallRelief: 'Shift relief',
      recallReassigned: 'Reassignment',
      recallNotesLabel: 'Return observations',
      recallNotesPh: 'Enter observations...',
      teamOperators: 'operators',
      sectorModalTitle: 'Sector',
      sectorActionLabel: 'Required action',
      sectorActionPatrol: 'Request patrol',
      sectorActionInspect: 'Physical inspection',
      sectorActionLockdown: 'Activate sector lockdown',
      sectorActionReport: 'Log event',
      sectorNotesLabel: 'Observations',
      sectorNotesPh: 'Describe the observed situation...',
      sectorExecute: 'Execute action',
      teamToast: 'forward position',
      teamStandbyToast: 'standby',
      teamStatus: {
        standby: 'STANDBY',
        deployed: 'DEPLOYED',
        responding: 'RESPONDING',
      },
    },
    /* ── Surveillance Center ── */
    surv: {
      title: 'Surveillance Center',
      subtitle: 'CCTV grid · AI video analytics · camera health monitoring',
      titleFull: 'Surveillance & Security Intelligence Center',
      subtitleFull: 'Centralized CCTV operations · AI detection engine · Perimeter intelligence · Incident correlation',
      cameraGrid: 'Camera Grid',
      cameraHealth: 'Camera Health',
      aiActivity: 'AI Detection Activity',
      onlineCameras: 'Online Cameras',
      offlineCameras: 'Offline Cameras',
      flaggedCameras: 'AI Flagged',
      totalCameras: 'Total Cameras',
      criticalDetections: 'Critical Detections',
      openIncidents: 'Open Incidents',
      threatScore: 'Threat Score',
      facilityCoverage: 'facility-wide coverage',
      pctOperational: '% operational',
      maintenanceReq: 'maintenance required',
      unresolvedCritical: 'unresolved critical events',
      activeInvestigations: 'active investigations',
      aiFlag: 'AI Flag',
      recordingAllCams: 'Recording active on all online cameras',
      noCamsFilter: 'No cameras match current filter',
      liveCamMatrix: 'Live Camera Matrix',
      camInspector: 'Camera Inspector',
      aiDetEngine: 'AI Detection Engine',
      incCorrEngine: 'Incident Correlation Engine',
      incCorrSubtitle: 'AI-linked multi-event security correlation · Behavioral pattern synthesis · Predictive threat assessment',
      perimSecIntel: 'Perimeter Security Intelligence',
      perimSubtitle: 'Fence sensors · Thermal cameras · Motion detection · Guard towers · UAV surveillance',
      thermalAnalytics: 'Thermal Analytics',
      thermalSubtitle: 'Infrared detection feed · Signature classification engine',
      threatEscDash: 'Threat Escalation Dashboard',
      threatEscSubtitle: 'Facility-wide security posture',
      aiPredAnalytics: 'AI Predictive Analytics',
      aiPredSubtitle: 'Zone risk forecasting · Behavioral anomaly detection · Threat prediction models',
      selectCamera: 'Select a camera',
      cameraId: 'Camera ID',
      online: 'ONLINE',
      offline: 'OFFLINE',
      frameRate: 'Frame Rate',
      resolution: 'Resolution',
      aiFlags: 'AI Flags',
      encryption: 'Encryption',
      retention: 'Retention',
      protocol: 'Protocol',
      networkHealth: 'Network Health',
      storageUtil: 'Storage Utilization',
      recordingActive: 'RECORDING ACTIVE',
      recordingSuspended: 'RECORDING SUSPENDED',
      continuousRec: 'Continuous recording · Cloud backup enabled',
      lastKnownState: 'Last known state preserved',
      activeAiDetections: 'Active AI Detections',
      envConditions: 'Environmental Conditions',
      visibility: 'Visibility',
      lighting: 'Lighting',
      temperature: 'Temperature (amb.)',
      humidity: 'Humidity',
      good: 'Good',
      adequate: 'Adequate',
      unknown: 'Unknown',
      allCameras: 'All',
      flaggedFilter: 'Flagged',
      offlineFilter: 'Offline',
      noMatch: 'No camera matches the selected filter',
      selected: 'Selected',
      aiActive: 'AI ACTIVE',
      signalLost: 'SIGNAL LOST',
      liveFeed: 'LIVE FEED',
      allFilter: 'All',
      criticalFilter: 'Critical',
      highFilter: 'High',
      activeFilter: 'Active',
      noDetections: 'No detections match current filter',
      statusBreakdown: 'Status Breakdown',
      mostActiveZones: 'Most Active Zones',
      threatDist: 'Threat Distribution',
      linkedEvents: 'Linked Detection Events',
      affectedAreas: 'Affected Areas',
      assocInmates: 'Associated Inmates',
      predictedOutcome: 'Predicted Outcome',
      recommendedAction: 'Recommended Action',
      currentThreatLevel: 'CURRENT THREAT LEVEL',
      secPostureScale: 'Security Posture Scale',
      activeEmergencies: 'Active Emergencies',
      lockdownEffect: 'LOCKDOWN IN EFFECT',
      lockdownZoneSuffix: 'zone under active lockdown protocol',
      lockdownZonesSuffix: 'zones under active lockdown protocol',
      noActiveEmergencies: 'NO ACTIVE EMERGENCIES',
      allProtocolsNormal: 'All protocols within normal parameters',
      highRiskAreas: 'High-Risk Areas (24h)',
      behavioralAnomalies: 'Behavioral Anomalies Detected',
      secRecommendations: 'Security Recommendations',
      respTeamReadiness: 'Response Team Readiness',
      aiReasoning: 'AI Reasoning',
      classificationKey: 'Classification Key',
      humanDetection: 'Human Detection',
      vehicleDetection: 'Vehicle Detection',
      animalDetection: 'Animal Detection',
      unknownHeat: 'Unknown Heat Signature',
      lastRecordedEvent: 'Last Recorded Event',
      aiThreatAssessment: 'AI Threat Assessment',
      fenceSensors: 'Fence Sensors',
      thermalCameras: 'Thermal Cameras',
      motionSensors: 'Motion Sensors',
      guardTowers: 'Guard Towers',
      uavSurveillance: 'UAV Surveillance',
      uavActive: 'active',
      offlineCritical: 'OFFLINE',
      criticalLabel: 'CRITICAL',
      recordingChip: 'RECORDING',
      perimRiskLabel: 'RISK',
      perimIntrusionSingular: 'INTRUSION',
      perimIntrusionPlural: 'INTRUSIONS',
      perimStatusAlert: 'ALERT', perimStatusNormal: 'NORMAL', perimStatusCaution: 'CAUTION',
      perimLabelN: 'North Perimeter', perimLabelE: 'East Perimeter', perimLabelS: 'South Perimeter', perimLabelW: 'West Perimeter',
      tempLabel: 'TEMP', confLabel: 'CONF', moveLabel: 'MOVE',
      threatLabelGreen: 'NORMAL', threatLabelYellow: 'HEIGHTENED', threatLabelOrange: 'HIGH ALERT', threatLabelRed: 'CRITICAL INCIDENT', threatLabelBlack: 'FACILITY EMERGENCY',
      threatDescGreen: 'Facility operating within normal parameters. No immediate threats identified.',
      threatDescYellow: 'Elevated threat indicators present. Increased monitoring and patrol density required.',
      threatDescOrange: 'Active security threats confirmed. Response teams deployed. Command staff notified.',
      threatDescRed: 'Major security incident in progress. All response units engaged. External agencies on standby.',
      threatDescBlack: 'Facility-wide emergency declared. Maximum response posture. External agencies activated.',
      detStatusDetecting: 'Detecting', detStatusVerifying: 'Verifying', detStatusConfirmed: 'Confirmed', detStatusResponding: 'Responding', detStatusResolved: 'Resolved',
      detFight: 'Fight Detection', detWeap: 'Weapon Detection', detGang: 'Gang Assembly', detFenc: 'Fence Climbing', detGurd: 'Guard Distress Event',
      detUent: 'Unauthorized Entry', detFire: 'Fire Detection', detAggr: 'Aggressive Behavior', detGath: 'Unauthorized Gathering', detDoor: 'Cell Door Tampering',
      detMed: 'Medical Emergency', detCtrb: 'Contraband Exchange', detCrwd: 'Abnormal Crowd Formation', detRacc: 'Restricted Area Access',
      detRun: 'Running — Restricted Zone', detSmok: 'Smoke Detection', detSobj: 'Suspicious Object', detVisv: 'Visitor Screening Violation',
      detFall: 'Fall Detection', detNact: 'Unusual Night Activity',
      detLab0: 'Unauthorized movement detected', detLab1: 'Unidentified gathering forming', detLab2: 'Restricted zone breach', detLab3: 'Contraband indicator present', detLab4: 'Cell door manipulation',
      behav1: 'Subject CR-2048 — behavioral deviation +2.7σ', behav2: 'Block B — coordinated movement pattern active', behav3: 'North fence — repeated probing sub-pattern', behav4: 'West loading bay — unauthorized vehicle access',
      escaleTitle: 'Escalate AI detection', escaleResponse: 'Required response', escaleDispatch: 'Dispatch response team', escaleVerify: 'Physical verification',
      escaleLockdown: 'Zone lockdown', escaleMedical: 'Medical response', escaleLog: 'Log only', escaleTeam: 'Team to dispatch',
      escalePriority: 'Priority', escaleCritical: 'Critical — immediate response', escaleHigh: 'High — within 5 minutes', escaleModerate: 'Moderate — within 15 minutes',
      escaleNotes: 'Operator observations', escaleNotesPh: 'Describe the observed situation...', escaleConfirm: 'Escalate and dispatch',
      camActionTitle: 'Camera action', camZone: 'Zone', camStatus: 'Status', camOperative: 'Operative', camOffline: 'Offline',
      camActionLabel: 'Required action', camPtz: 'PTZ adjustment (angle/zoom)', camMaint: 'Request maintenance', camReview: 'Review flagged recordings',
      camSnapshot: 'Capture evidence snapshot', camReset: 'Reset camera', camActionDesc: 'Action description', camActionDescPh: 'Describe the reason for the action...', camActionConfirm: 'Execute action',
    },
    /* ── Incident Management ── */
    inc: {
      title: 'Incident Management',
      subtitle: 'Full lifecycle case management from report to closure',
      boardTitle: 'Incident Lifecycle Board',
      boardSub: 'Drag-free kanban — click a card for the full case file',
      logTitle: 'Incident Log',
      distTitle: 'Incident Type Distribution',
      thId: 'ID', thType: 'Type', thSev: 'Severity', thZone: 'Zone',
      thStage: 'Stage', thCmd: 'Commander', thRep: 'Reported',
      metricOpen: 'Open Incidents',
      subNotYetClosed: 'not yet closed',
      metricInResponse: 'In Active Response',
      subTeamsEngaged: 'teams engaged',
      metricClosed: 'Closed (30d)',
      subResolvedCases: 'resolved cases',
      newTitle: 'New Report',
      newSubtitle: 'Register a new incident in the system',
      typeLabel: 'Incident type',
      teamLabel: 'Response team',
      descLabel: 'Incident description',
      descPh: 'Describe the incident in as much detail as possible...',
      cmdPh: 'Commander name',
      confirmLog: 'Register incident',
      typeAltercation: 'Altercation / Fight',
      typeContraband: 'Contraband detected',
      typeMedical: 'Medical Emergency',
      typeBreach: 'Security Breach',
      typeEscape: 'Escape Attempt',
      typeDisturbance: 'Disturbance',
      typeOther: 'Other',
      sevCritical: 'Critical',
      sevHigh: 'High',
      sevMedium: 'Medium',
      sevLow: 'Low',
      modalSummary: 'Summary',
      modalCmdr: 'Commander',
      modalTeam: 'Response team',
      modalCasualties: 'Casualties',
      modalStage: 'Current stage',
      modalSubjects: 'Subjects involved',
      modalRegistered: 'registered',
      modalAgo: 'ago',
      modalCasualtyWarn: 'casualties',
      btnAdvance: 'ADVANCE STAGE',
      btnAssign: 'ASSIGN COMMANDER',
      emptyKanban: '— empty —',
      advanceTitle: 'Advance incident stage',
      advanceNewStage: 'New stage',
      advanceNotesLabel: 'Progress notes',
      advanceNotesPh: 'Describe the progress and actions taken...',
      advanceOfficerLabel: 'Updating officer',
      advanceOfficerPh: 'Badge number or name',
      advanceConfirm: 'Advance stage',
      assignTitle: 'Assign commander',
      assignCmdLabel: 'Commander',
      assignCmdPh: 'Name and badge number',
      assignTeamLabel: 'Response team',
      assignTeamPh: 'Assigned team name',
      assignPriorityLabel: 'Response priority',
      assignImmediate: 'Immediate',
      assignUrgent: 'Urgent',
      assignNormal: 'Normal',
      assignInstructLabel: 'Instructions to commander',
      assignInstructPh: 'Enter corresponding instructions...',
      assignConfirm: 'Assign commander',
    },
    /* ── Inmate Intelligence ── */
    intel: {
      title: 'Inmate Intelligence',
      subtitle: 'Population profiling · association analysis · behavioral monitoring',
      riskStrat: 'Risk Stratification',
      crimeDistrib: 'Crime Category Distribution',
      watchlist: 'Critical Watchlist',
      popSummary: 'Population Summary',
      assocGraph: 'Association Graph',
      profileDossier: 'Subject Dossier',
      intFlags: 'Intelligence Flags',
      associates: 'Known Associates',
      thId: 'ID', thName: 'Name', thCrime: 'Crime Type', thCustody: 'Custody Level',
      thRisk: 'Risk', thThreat: 'Threat Score', thZone: 'Zone', thStatus: 'Status',
      thNat: 'Nationality', thFlags: 'Flags',
      filterAll: 'All',
      filterExtreme: 'Extreme',
      filterHigh: 'High',
      filterMed: 'Med',
      filterLow: 'Low',
      filterAllCrimes: 'All Crime Types',
      metricTotalPop: 'Total Population',
      subActiveCustody: 'active custody',
      metricViolent: 'Violent Offenders',
      metricAvgThreat: 'Avg Threat Score',
      sub0To100: '0–100 composite',
      rosterTitle: 'Population Roster',
      rosterOf: 'of',
      rosterSubjects: 'subjects',
      searchIdName: 'Search ID / name…',
      moreResults: 'more — refine filters to narrow results',
      threatLabel: 'THREAT',
      riskPctPop: '% of pop.',
      kvCustodyLevel: 'Custody Level',
      kvThreatScore: 'Threat Score',
      kvHousing: 'Housing',
      kvStatus: 'Status',
      kvSentence: 'Sentence',
      kvYears: 'years',
      kvTimeServed: 'Time served',
      kvLastIncident: 'Last incident',
      kvNoRecord: 'No record',
      kvDaysAgo: 'days ago',
      kvAge: 'Age',
      noFlags: 'No active flags.',
      noAssociates: 'No associates registered in current population.',
      knownLabel: 'known',
      btnTransfer: 'TRANSFER',
      flagTypeLabel: 'Flag type',
      flagEscape: 'Escape risk',
      flagGang: 'Gang affiliation',
      flagContraband: 'Contraband involvement',
      flagViolence: 'Violence risk',
      flagInformant: 'Active informant',
      flagProtective: 'Requires protective custody',
      flagPriorityLabel: 'Surveillance priority',
      flagJustLabel: 'Flag justification',
      flagJustPh: 'Describe the reason for adding this intelligence flag...',
      transferTitle: 'Transfer inmate',
      transferCurrentZone: 'Current zone',
      transferCurrentCell: 'Cell',
      transferDestLabel: 'Destination zone',
      transferDestMAX: 'Maximum Security Wing',
      transferDestBLKA: 'Block A',
      transferDestBLKB: 'Block B',
      transferDestBLKC: 'Block C',
      transferDestMED: 'Medical Wing',
      transferDestISO: 'Isolation Unit',
      transferReasonLabel: 'Transfer reason',
      transferSecurity: 'Security reasons',
      transferMedical: 'Medical treatment',
      transferBehavioral: 'Inappropriate conduct',
      transferProtection: 'Protective custody',
      transferCourt: 'Court hearing',
      transferNotesLabel: 'Additional observations',
      transferNotesPh: 'Enter details about the transfer...',
      transferConfirm: 'Authorize transfer',
      priorityCritical: 'Critical',
      priorityHigh: 'High',
      priorityMedium: 'Medium',
    },
    /* ── AI Analytics ── */
    ai: {
      title: 'AI Analytics',
      subtitle: 'Predictive threat modelling · behavioral pattern analysis · intelligence fusion',
      forecastTitle: 'Threat Forecast',
      riskStrat: 'Population Risk Stratification',
      modelsTitle: 'Active AI Models',
      modelsSub: 'Inference pipeline status',
      recsTitle: 'Priority Recommendations',
      recsSub: 'AI-generated operational guidance',
      crimeProfile: 'Crime Category Threat Profile',
      crimeProfileSub: 'Avg AI threat score per crime category',
      topSignals: 'Top Intelligence Signals',
      topSignalsSub: 'Highest-confidence threat indicators',
      model1Title: 'Threat Escalation Predictor',
      model1Desc: 'LSTM-based temporal model · 72h forecast window · trained on 5y incident data',
      model2Title: 'Behavioral Pattern Mapper',
      model2Desc: 'Graph neural network · inmate co-occurrence · crime pattern correlation · behavioral deviation analysis',
      model3Title: 'Violence Risk Scorer',
      model3Desc: 'Gradient boost ensemble · behavioural features · historical incidents',
      model4Title: 'Contraband Flow Detector',
      model4Desc: 'Anomaly detection · visitor pattern analysis · movement correlation',
      model5Title: 'Escape Risk Classifier',
      model5Desc: 'Random forest · perimeter events · movement logs · psych flags',
      model6Title: 'Recidivism Predictor',
      model6Desc: 'Cox proportional hazards · rehabilitation programme outcomes',
      modelStatusActive: 'active',
      modelStatusTraining: 'training',
      metricAiThreat: 'AI Threat Index',
      subCompositeScore: 'composite model score 0–100',
      metricModelsRunning: 'Models Running',
      subRealTimeInference: 'real-time inference',
      metricAvgAccuracy: 'Avg Model Accuracy',
      subAcrossModels: 'across active models',
      trendViolenceRisk: 'Violence Risk Trend',
      trendModelConf: 'Model Confidence',
      trendEscapeRisk: 'Escape Risk Score',
      labelAccuracy: 'Accuracy',
      labelSubjects: 'subjects',
      labelConf: 'conf.',
      modelsActiveChip: 'MODELS ACTIVE',
      recExecTitle: 'Execute AI recommendation',
      recTeamLabel: 'Assigned team',
      recUrgencyLabel: 'Execution urgency',
      recUrgencyImmediate: 'Immediate',
      recUrgencyPriority: 'Priority (< 2 hours)',
      recUrgencyScheduled: 'Scheduled',
      recAuthLabel: 'Authorization type',
      recAuthStandard: 'Standard authorization',
      recAuthCommander: 'Commander approval required',
      recAuthDirector: 'Director approval required',
      recNotesLabel: 'Operator notes',
      recNotesPh: 'Enter additional observations...',
      recConfirm: 'Execute recommendation',
      modelConfigTitle: 'Configure model',
      modelActionLabel: 'Model action',
      modelRetrain: 'Start retraining',
      modelCalibrate: 'Recalibrate parameters',
      modelPause: 'Pause inference',
      modelExport: 'Export performance metrics',
      modelThresholdLabel: 'Confidence threshold (%)',
      modelThresholdPh: 'e.g. 80',
      modelJustLabel: 'Technical justification',
      modelJustPh: 'Describe the reason for this action...',
      modelApply: 'Apply configuration',
      minAgo: 'min ago',
      hAgo: 'h ago',
    },
    /* ── Staff Operations ── */
    staff: {
      title: 'Staff Operations',
      subtitle: 'Personnel roster · shift deployment · clearance management',
      totalPersonnel: 'Total Personnel',
      onDuty: 'On Duty',
      inResponse: 'In Active Response',
      offDuty: 'Off Duty / Leave',
      roster: 'Personnel Roster',
      shiftReadiness: 'Shift Readiness',
      roleDist: 'Role Distribution',
      zoneDeploy: 'Zone Deployment',
      thBadge: 'Badge', thName: 'Name', thRole: 'Role', thShift: 'Shift',
      thStatus: 'Status', thZone: 'Zone', thClearance: 'Clearance',
      subAll: 'all shifts combined',
      subForce: 'of force',
      subIncident: 'incident deployment',
      subUnavail: 'unavailable',
      shiftAll: 'All',
      searchStaff: 'Search name / badge / role…',
      shiftPrefix: 'SHIFT',
      activeDeployPct: '% active deployment',
      addModalTitle: 'Add staff to shift',
      addModalSubtitle: 'Register a staff assignment to the active shift',
      nameLabel: 'Full name',
      namePh: 'First and last name',
      badgeLabel: 'Badge number',
      badgePh: 'e.g. CO-4821',
      roleLabel: 'Role',
      roleCorrections: 'Corrections Officer',
      roleTactical: 'Tactical Officer',
      roleMedical: 'Medical Staff',
      roleAnalyst: 'Intelligence Analyst',
      roleSupervisor: 'Supervisor',
      shiftLabel: 'Assigned shift',
      zoneLabel: 'Assignment zone',
      clearanceLabel: 'Clearance level',
      clearance1: 'Level 1',
      clearance2: 'Level 2',
      clearance3: 'Level 3',
      clearance4: 'Level 4',
      clearance5: 'Level 5 (maximum)',
      confirmAddStaff: 'Register staff',
      reassignTitle: 'Reassign staff',
      newZoneLabel: 'New assignment zone',
      missionLabel: 'Mission type',
      missionPatrol: 'Patrol',
      missionResponse: 'Incident response',
      missionEscort: 'Escort',
      missionGuard: 'Fixed guard',
      durationLabel: 'Mission duration',
      dur1h: '1 hour',
      dur4h: '4 hours',
      durShift: 'Full shift',
      instrLabel: 'Special instructions',
      instrPh: 'Enter additional instructions...',
      confirmReassign: 'Reassign staff',
      kvStatus: 'Status',
      kvShift: 'Shift',
      kvZone: 'Assigned zone',
      kvClearance: 'Security clearance',
      kvYearsService: 'Years of service',
      notAssigned: 'Not assigned',
      clearancePrefix: 'LEVEL',
      btnReassign: 'REASSIGN',
      btnClose: 'CLOSE',
      officersLabel: 'officers',
    },
    /* ── Rehabilitation Programs ── */
    rehab: {
      title: 'Rehabilitation Programs',
      subtitle: 'Education · vocational training · psychological support · reintegration',
      programsActive: 'Programs Active',
      totalEnrolled: 'Total Enrolled',
      avgCompletion: 'Avg Completion Rate',
      totalCapacity: 'Total Capacity',
      activePrograms: 'Active Programs',
      categoryOverview: 'Category Overview',
      compliance: 'Compliance Indicators',
      programRegister: 'Program Register',
      thId: 'ID', thProgram: 'Program', thCategory: 'Category', thFacilitator: 'Facilitator',
      thEnrolled: 'Enrolled', thCapacity: 'Capacity', thUtil: 'Utilization', thCompletion: 'Completion',
      subAllCat: 'all categories',
      subPop: 'of population',
      subAcross: 'across all programs',
      subUtil: 'utilization',
      enrolled: 'ENROLLED',
      avgComp: 'AVG COMPLETION',
      catAll: 'All',
      catEducation: 'Education',
      catVocational: 'Vocational',
      catPsych: 'Psych',
      catSubstance: 'Substance',
      catReintegration: 'Reintegration',
      cardEnrollment: 'Enrollment',
      cardCompletionRate: 'Completion Rate',
      categoryEnrolled: 'Enrolled',
      categoryAvgComp: 'Avg Completion',
      compliancePsychHours: 'Mandatory Psych Hours',
      complianceEducationQuota: 'Education Quota',
      complianceSubstance: 'Substance Counselling',
      complianceRecidivism: 'Recidivism Tracking',
      complianceAnnualReport: 'Annual Ministry Report',
      complianceDueIn42d: 'DUE IN 42d',
      complianceCompliant: 'COMPLIANT',
      complianceActive: 'ACTIVE',
      noPrograms: 'No programs in this category.',
      programsCount: 'programs',
      addModalSubtitle: 'Register a new rehabilitation program in the system',
      programNameLabel: 'Program name',
      programNamePh: 'Descriptive program name',
      facilitatorPh: 'Responsible facilitator name',
      capacityPh: 'e.g. 20',
      scheduleLabel: 'Schedule',
      schedulePh: 'e.g. Mon & Wed 09:00–11:00',
      descLabel: 'Program description',
      descPh: 'Describe the objectives and methodology of the program...',
      enrollModalAvailSlots: 'Available slots',
      enrollModalCompletionRate: 'Completion rate',
      enrollInmateLabel: 'Inmate ID',
      enrollInmatePh: 'e.g. CR-1234',
      enrollMotivLabel: 'Enrollment motivation',
      enrollVoluntary: 'Voluntary participation',
      enrollMandatory: 'Court requirement',
      enrollRecommended: 'Program recommendation',
      enrollParole: 'Parole requirement',
      enrollStartLabel: 'Start date',
      enrollStartPh: 'DD/MM/YYYY',
      enrollNotesLabel: 'Enrollment notes',
      enrollNotesPh: 'Enter relevant observations...',
      kvCategory: 'Category',
      kvFacilitator: 'Facilitator',
      kvEnrolledCapacity: 'Enrolled / Capacity',
      kvUtilization: 'Utilization',
      kvCompletionRate: 'Completion Rate',
      btnClose: 'Close',
      addProgramConfirm: 'Register program',
    },
    /* ── Digital Twin ── */
    twin: {
      title: 'Digital Twin',
      subtitle: 'Real-time schematic model of CACCO physical plant',
      schematic: 'Facility Schematic — Sector Overview',
      schematicSub: 'Click a zone to inspect · color encodes selected layer',
      zoneDetail: 'Zone Detail',
      layers: 'Map Layers',
      live: 'LIVE',
      layerStatus: 'Status', layerOccupancy: 'Occupancy', layerIncidents: 'Incidents', layerPersonnel: 'Personnel',
      heatmapNone: 'None', heatmapViolence: 'Violence Risk', heatmapContraband: 'Contraband', heatmapGang: 'Gang Activity',
      overlayGuards: 'Guards', overlayInmates: 'Inmates', overlayAi: 'AI Layer', overlayHeatmap: 'Heatmap', overlayDoors: 'Doors',
      guardsLabel: 'guards', active: 'ACTIVE', lockdownActive: 'LOCKDOWN ACTIVE', lockdownBtn: 'LOCKDOWN',
      tabOverview: 'Overview', tabGuards: 'Guards', tabCameras: 'Cameras', tabSensors: 'Sensors', tabAi: 'AI', tabDoors: 'Doors',
      clickZone: 'Click a zone to inspect',
      riskLevel: 'Risk Level', incidents24h: 'Incidents 24h', guardsOnSite: 'Guards On-Site',
      facilitySummary: 'FACILITY SUMMARY', totalZones: 'Total Zones', camerasOnline: 'Cameras Online',
      sensorsActive: 'Sensors Active', sensorFaults: 'Sensor Faults', guardsDeployed: 'Guards Deployed', activeInc: 'Active Incidents',
      activeIncTitle: 'ACTIVE INCIDENTS', aiPredTitle: 'AI PREDICTIONS',
      deployedGuardsTitle: 'DEPLOYED GUARDS', allCamerasTitle: 'ALL CAMERAS', allSensorsTitle: 'ALL SENSORS',
      badge: 'Badge', radio: 'Radio', clearanceLevel: 'Level',
      aiFlags: 'AI Flags', recording: 'Recording', angle: 'Angle', fov: 'FoV',
      kvId: 'ID', battery: 'Battery', lastEvent: 'Last Event', sensorLabel: 'SENSOR',
      dispatchGuard: 'Dispatch Guard', medicalTeam: 'Medical Team', tactical: 'Tactical',
      prob: 'Prob', window: 'Window', conf: 'Conf',
      aiThreatTitle: 'AI THREAT ASSESSMENT', behavIntel: 'BEHAVIORAL INTEL',
      confidence: 'Confidence', accessControl: 'ACCESS CONTROL', doorsLabel: 'DOORS',
      unlock: 'UNLOCK', lock: 'LOCK', timeline: 'TIMELINE', events: 'events',
      yes: 'YES', no: 'NO', more: 'more', zonePrefix: 'ZONE',
    },
    /* ── Reports & Compliance ── */
    rpt: {
      title: 'Reports & Compliance',
      subtitle: 'Statutory reporting · audit trail · Ministry of Justice and Peace submissions',
      scheduleTitle: 'Report Schedule',
      auditTitle: 'Audit Log',
      statsTitle: 'Compliance Statistics',
      thId: 'ID', thReport: 'Report', thCategory: 'Category', thFreq: 'Frequency',
      thLast: 'Last Generated', thNext: 'Next Due', thStatus: 'Status', thRecipient: 'Recipient',
      thTime: 'Time', thAction: 'Action', thUser: 'User', thRef: 'Reference',
      exportBtn: 'EXPORT PDF',
      statusCurrent: 'CURRENT',
      statusDueSoon: 'DUE SOON',
      statusOverdue: 'OVERDUE',
      metricTemplates: 'Report Templates',
      subScheduled: 'scheduled reports',
      metricGenerated: 'Generated (30d)',
      subTransmitted: 'successfully transmitted',
      metricDueSoon: 'Due Soon',
      subWithin3d: 'within 3 days',
      metricOverdue: 'Overdue',
      subImmediateAction: 'immediate action required',
      reportRegistryTitle: 'Report Registry',
      reportRegistrySub: 'Statutory and operational report schedule',
      complianceDashTitle: 'Compliance Dashboard',
      quickExportTitle: 'Quick Export',
      auditSub: 'System and user action log — classification: RESTRICTED',
      auditSeverity: 'Severity',
      chipOverdue: 'OVERDUE',
      chipDueSoon: 'DUE SOON',
      idhab: 'IDHAB Human Rights',
      mjsp: 'MJSP Reporting',
      oij: 'OIJ Intelligence Share',
      nationalAudit: 'National Security Audit',
      inmateRights: 'Inmate Rights Protocol',
      segregation: 'Segregation Time Limits',
      medicalAccess: 'Medical Access Standards',
      visitorProcessing: 'Visitor Processing Time',
      dataRetention: 'Data Retention Policy',
      auditLoggingLabel: 'System Audit Log',
      compCompliant: 'COMPLIANT',
      compInReview: 'IN REVIEW',
      compScheduled: 'SCHEDULED',
      compAttention: 'ATTENTION',
      compActive: 'ACTIVE',
      qePopulation: 'Current Population Snapshot',
      qeIncidents: 'Active Incidents Summary',
      qeAlerts: 'Security Alert Log (24h)',
      qeStaff: 'Staff Roster (Current Shift)',
      qeIntelligence: 'Intelligence Briefing',
      exportFormatLabel: 'Export format',
      exportFormatPdf: 'PDF (classified)',
      exportFormatXlsx: 'Excel (.xlsx)',
      exportFormatCsv: 'CSV (raw data)',
      exportClassLabel: 'Classification level',
      exportClassRestricted: 'RESTRICTED',
      exportClassConfidential: 'CONFIDENTIAL',
      exportClassSecret: 'SECRET',
      exportRecipientLabel: 'Additional recipient',
      exportRecipientPh: 'Institutional email or recipient name',
      exportNotesLabel: 'Transmission notes',
      exportNotesPh: 'Observations to include in transmission...',
      schedModalSubtitle: 'Configure automatic generation of a new report',
      schedTitleLabel: 'Report title',
      schedTitlePh: 'Descriptive report name',
      schedCategoryLabel: 'Category',
      schedCatOps: 'Operations',
      schedCatSecurity: 'Security',
      schedCatIntel: 'Intelligence',
      schedCatRehab: 'Rehabilitation',
      schedCatCompliance: 'Compliance',
      schedCatGov: 'Governance',
      schedFreqLabel: 'Frequency',
      schedFreqDaily: 'Daily',
      schedFreqWeekly: 'Weekly',
      schedFreqMonthly: 'Monthly',
      schedFreqQuarterly: 'Quarterly',
      schedFreqAnnual: 'Annual',
      schedRecipientLabel: 'Primary recipient',
      schedRecipientPh: 'Name or recipient institution',
      viewPeriodLabel: 'Report period',
      viewPeriodLast: 'Last generated version',
      viewPeriod7d: 'Last 7 days',
      viewPeriod30d: 'Last 30 days',
      viewPeriod90d: 'Last 90 days',
      viewNotesLabel: 'Review observations',
      viewNotesPh: 'Record your review observations...',
      viewConfirm: 'View report',
      viewTitle: 'View report',
      viewLastGen: 'Last generated',
      exportRecipientDefault: 'Recipient',
      chipRecipient: 'Recipient',
    },
    /* ── System Admin ── */
    admin: {
      title: 'System Administration',
      subtitle: 'Service health · access control · integrations · security configuration',
      servicesTitle: 'Service Health',
      accessTitle: 'Access Control & Sessions',
      integrationsTitle: 'External Integrations',
      servicesOnline: 'Services Online',
      avgLatency: 'Avg Latency',
      sessions: 'Active Sessions',
      mfaAlert: 'MFA Non-Compliant',
      thId: 'ID', thService: 'Service', thStatus: 'Status', thLatency: 'Latency',
      thUptime: 'Uptime', thCategory: 'Category',
      thUser: 'User', thRole: 'Role', thClearance: 'Clearance',
      thLastLogin: 'Last Login', thMFA: 'MFA',
      serviceHealthTitle: 'Service Health Monitor',
      serviceHealthSub: 'Real-time service availability and latency',
      systemHealthTitle: 'System Health',
      secConfigTitle: 'Security Config',
      maintenanceTitle: 'Maintenance & Actions',
      subAvgUptime: 'avg uptime',
      subResponseTime: 'response time',
      subAuthUsers: 'authenticated users',
      subWithout2FA: 'users without 2FA',
      colHealth: 'Health',
      statusOnline: 'ONLINE',
      statusDegraded: 'DEGRADED',
      statusOffline: 'OFFLINE',
      mfaEnabled: 'ENABLED',
      mfaDisabled: 'DISABLED',
      chipDegraded: 'DEGRADED',
      chipOperational: 'OPERATIONAL',
      kvServicesOnline: 'Services Online',
      kvApiLatency: 'API Latency',
      kvSystemStatus: 'System Status',
      kvLastBackup: 'Last Backup',
      kvDiskUsage: 'Disk Usage',
      kvEncryption: 'Encryption',
      kvMfaPolicy: 'MFA Policy',
      kvSessionTimeout: 'Session Timeout',
      kvFailedLogin: 'Failed Login Lockout',
      kvAuditLogging: 'Audit Logging',
      kvDataClass: 'Data Classification',
      kvLastPentest: 'Last Pentest',
      kvEnforced: 'ENFORCED',
      kvPartial: 'PARTIAL',
      kvEnabled: 'ENABLED',
      kvRestricted: 'RESTRICTED',
      maintRotateCodes: 'Rotate Access Codes',
      maintClearAiCache: 'Clear AI Cache',
      maintExportAudit: 'Export Audit Log',
      maintSyncMjsp: 'Sync MJSP Link',
      maintDiagnostics: 'System Diagnostics',
      maintEmergencyShutdown: 'Emergency Shutdown',
      addUserModalSubtitle: 'Register a new user in the access control system',
      nameLabel: 'Full name',
      namePh: 'Staff first and last name',
      roleDirector: 'Director',
      roleCommander: 'Commander',
      roleAnalyst: 'Intelligence Analyst',
      roleSecOfficer: 'Security Officer',
      roleMedical: 'Medical',
      roleMaintenance: 'Maintenance',
      clearancePrefix: 'Level',
      clearance5Max: 'Level 5 (Maximum)',
      mfaLabel: 'MFA Authentication',
      mfaEnabledRequired: 'Enabled (required)',
      mfaDisabledNotRec: 'Disabled (not recommended)',
      confirmAddUser: 'Register user',
      editUserTitle: 'Edit user',
      mfaStatusLabel: 'MFA status',
      mfaStatusEnabled: 'Enabled',
      mfaStatusDisabled: 'Disabled',
      reasonLabel: 'Reason for change',
      reasonPh: 'Describe the reason for the modification...',
      saveChanges: 'Save changes',
      maintModalSubtitle: 'Confirm the parameters of this operation before executing',
      authCodeLabel: 'Authorization code',
      authCodePh: 'Enter your authorization code',
      maintJustLabel: 'Operational justification',
      maintJustPh: 'Describe the reason for this action...',
      maintScheduleLabel: 'Scheduling',
      maintNow: 'Execute immediately',
      maintWindow: 'During maintenance window',
      maintOffPeak: 'Off-peak hours (00:00–06:00)',
      maintConfirmPrefix: 'Execute',
      accessTableSubtitle: 'Authenticated accounts and clearance levels',
    },
    /* Common */
    common: {
      viewDetails: 'VIEW DETAILS',
      execute: 'EXECUTE RECOMMENDATION',
      close: 'Close',
      cancel: 'Cancel',
      confirm: 'Confirm',
      save: 'Save',
      submit: 'Submit',
      ack: 'ACK',
      search: 'Search',
      active: 'ACTIVE',
      officers: 'officers',
      ofPop: '% of pop.',
      modelConf: 'Model Confidence',
      noAlerts: 'No active alerts.',
      noPrograms: 'No programs in this category.',
      live: 'LIVE',
      occupancy: 'Occupancy',
      incidents: 'Incidents',
      personnel: 'Personnel',
      risk: 'Risk',
      zone: 'Zone',
      status: 'Status',
      resumeStream: 'Resume stream',
      pauseStream: 'Pause stream',
      high: 'HIGH',
      rdy: 'RDY',
      opr: 'OPR',
      sallyPort1: 'Sally Port 1',
      sallyPort2: 'Sally Port 2',
      vehicleGate: 'Vehicle Gate',
      droneOverwatch: 'Drone Overwatch',
      secured: 'SECURED',
      staged: 'STAGED',
      activeStatus: 'ACTIVE',
      cobra: 'COBRA',
      criticalRecs: 'CRITICAL RECS',
      highPriorityRecs: 'High-Priority Recs',
      requireImmediateReview: 'require immediate review',
      highestSeverity: 'highest severity',
      highRiskInmates: 'High-Risk Inmates',
      riskGreaterThanHigh: 'risk ≥ High',
      modalNotes: 'Observations',
      modalNotesPlaceholder: 'Enter corresponding observations...',
      modalPriority: 'Priority',
      modalZone: 'Affected zone',
      modalZonePlaceholder: 'Select a zone',
      modalTeam: 'Assigned team',
      modalTeamPlaceholder: 'Select a team',
      modalReason: 'Reason',
      modalReasonPlaceholder: 'Describe the reason for the action...',
      modalDuration: 'Estimated duration',
      modalIncidentType: 'Incident type',
      modalDescription: 'Incident description',
      modalDescPlaceholder: 'Describe the incident in detail...',
      modalReporter: 'Reported by',
      modalSeverity: 'Severity level',
      logIncident: 'LOG INCIDENT',
      orderLockdown: 'ORDER LOCKDOWN',
      deployTeam: 'DEPLOY TEAM',
      addPersonnel: 'ADD PERSONNEL',
      escalate: 'ESCALATE',
      acknowledge: 'ACKNOWLEDGE',
      dismiss: 'DISMISS',
      exportReport: 'EXPORT REPORT',
      scheduleReport: 'SCHEDULE REPORT',
      addProgram: 'ADD PROGRAM',
      enrollInmate: 'ENROLL INMATE',
      flagInmate: 'FLAG INMATE',
      generateReport: 'GENERATE REPORT',
      configService: 'CONFIGURE SERVICE',
      addUser: 'ADD USER',
      lockZone: 'LOCK ZONE',
      updateStatus: 'UPDATE STATUS',
      viewFullProfile: 'VIEW FULL PROFILE',
      zoneActions: 'ZONE ACTIONS',
    },
    tone: {
      op: { normal: 'NORMAL', elevated: 'ELEVATED', critical: 'CRITICAL', lockdown: 'LOCKDOWN' },
      risk: { low: 'LOW', medium: 'MEDIUM', high: 'HIGH', extreme: 'EXTREME' },
      threat: { info: 'INFO', low: 'LOW', moderate: 'MODERATE', high: 'HIGH', critical: 'CRITICAL' },
      priority: { low: 'LOW', medium: 'MEDIUM', high: 'HIGH', critical: 'CRITICAL' },
      alertStatus: { active: 'ACTIVE', dispatched: 'DISPATCHED', contained: 'CONTAINED', monitoring: 'MONITORING', resolved: 'RESOLVED' },
      stage: { reported: 'REPORTED', investigating: 'INVESTIGATING', response: 'RESPONSE', review: 'REVIEW', closed: 'CLOSED' },
      secLabel: { l1: 'NORMAL', l2: 'HEIGHTENED', l3: 'HIGH ALERT', l4: 'CRITICAL INCIDENT' },
      secCode: { l1: 'LEVEL 1', l2: 'LEVEL 2', l3: 'LEVEL 3', l4: 'LEVEL 4' },
      rag: { normal: 'NORMAL', warning: 'WARNING', critical: 'CRITICAL' },
    },
    kpi: {
      prevDay: 'PREV DAY', change: 'CHANGE', prevShift: 'PREV SHIFT',
      yesterday: 'YESTERDAY', trend: 'TREND', baseline: 'BASELINE', deviation: 'DEVIATION',
      nameInmates: 'Total Inmates', nameOccupancy: 'Facility Occupancy',
      nameAlerts: 'Active Security Alerts', nameHighrisk: 'High-Risk Inmates',
      namePersonnel: 'On-Duty Personnel', nameThreat: 'AI Threat Index',
    },
    cards: {
      action: 'Action', dismiss: 'Dismiss', modelConf: 'Model Confidence',
      src: 'SRC', recommended: 'Recommended', zoneLabel: 'Zone',
      reasoning: 'Reasoning', suggestedAction: 'Suggested Action',
      expectedOutcome: 'Expected Outcome', priority: 'PRIORITY',
    },
  },

  /* ──────────────────────── SPANISH ─────────────────────────────── */
  es: {
    nav: {
      group: {
        Command: 'Mando', Operations: 'Operaciones', Intelligence: 'Inteligencia',
        Facility: 'Instalaciones', Governance: 'Gobernanza',
      },
      item: {
        commandCenter: 'Centro de Mando',
        securityOps: 'Operaciones de Seguridad',
        surveillance: 'Centro de Vigilancia',
        incidents: 'Gestión de Incidentes',
        inmateIntel: 'Inteligencia Penitenciaria',
        aiAnalytics: 'Análisis de Inteligencia Artificial',
        staffOps: 'Operaciones de Personal',
        rehab: 'Programas de Rehabilitación',
        twin: 'Gemelo Digital',
        reports: 'Informes y Cumplimiento Normativo',
        admin: 'Administración del Sistema',
      },
    },
    layout: {
      platform: 'PLATAFORMA DE MANDO',
      logout: 'Cerrar sesión / Bloquear acceso',
      search: 'Buscar plataforma…  Ctrl+K',
      onDuty: 'EN SERVICIO',
      advisory: 'S!aP Asesoramiento',
      profileUser: 'Perfil',
      profileNotifications: 'Notificaciones',
      profileSettings: 'Configuración',
      profileOnline: 'En línea',
      profileEngineer: 'Ingeniero de Diseño',
      drawerIntelTitle: 'Inteligencia sobre Amenazas',
      drawerIntelSubActive: 'evaluaciones activas',
      drawerIntelAlerts: 'Alertas de Seguridad Activas',
      drawerIntelAssess: 'Evaluaciones de Inteligencia',
      drawerAdvisory: 'S!aP Asesoramiento',
      drawerAdvisorySubRecs: 'recomendaciones',
      footerRestricted: 'RESTRINGIDO',
      footerPlatform: 'Plataforma de Mando CACCO · Ministerio de Justicia y Paz de Costa Rica',
      footerDataRefresh: 'ACTUALIZACIÓN DE DATOS',
      footerNominal: 'SISTEMAS NORMALES',
      searchNoResults: 'Sin resultados para',
    },
    cc: {
      title: 'Centro de Mando',
      subtitle: 'Conciencia situacional en tiempo real · todas las zonas · todas las operaciones',
      strategicIndicators: 'Indicadores Estratégicos',
      opStatusTitle: 'Estado Operacional — Zonas del Establecimiento',
      opStatusSub: 'Ocupación en tiempo real, incidentes y estado de postura por zona',
      liveAlerts: 'Transmisión de Alertas en Tiempo Real',
      aiAdvisor: 'Asesor de Operaciones con IA',
      aiAdvisorSub: 'Recomendaciones de inteligencia penitenciaria',
      threatIntel: 'Inteligencia sobre Amenazas',
      threatIntelSub: 'Delincuencia · contrabando · conducta · perímetro',
      responseTitle: 'Disponibilidad de Equipos de Respuesta',
      responseSub: 'Estado de los equipos en tiempo real · capacidad de despliegue',
      facilityName: 'CENTRO DE ALTA CONTENCIÓN DEL CRIMEN ORGANIZADO',
      modalZoneActions: 'Acciones de Zona',
      modalZoneOccupancy: 'Ocupación',
      modalZoneRisk: 'Riesgo',
      modalActionLabel: 'Acción a ejecutar',
      modalPriorityLabel: 'Nivel de prioridad',
      optLockdown: 'Ordenar confinamiento',
      optPatrol: 'Solicitar patrullaje adicional',
      optIncident: 'Registrar incidente',
      optPersonnel: 'Asignar personal adicional',
      optCritical: 'Crítico',
      optHigh: 'Alto',
      optMedium: 'Medio',
      optLow: 'Bajo',
      executeAction: 'Ejecutar acción',
      toastAction: 'Acción ejecutada en',
      executeRec: 'Ejecutar recomendación',
      recTeamLabel: 'Equipo asignado',
      recTimeline: 'Plazo de ejecución',
      recOptImmediate: 'Inmediato (< 15 min)',
      recOpt1h: 'En 1 hora',
      recOpt4h: 'En 4 horas',
      recOptShift: 'En el siguiente turno',
      recNotesLabel: 'Observaciones del operador',
      recNotesPh: 'Ingrese observaciones adicionales...',
      ackTitle: 'Confirmar recepción de alerta',
      ackActionLabel: 'Acción tomada',
      ackOptDispatched: 'Equipo despachado',
      ackOptMonitoring: 'En monitoreo continuo',
      ackOptResolved: 'Resuelta sin intervención',
      ackOptEscalated: 'Escalada a comando',
      ackOfficerLabel: 'Funcionario responsable',
      ackOfficerPh: 'Número de placa o nombre',
      ackNotesLabel: 'Observaciones',
      ackNotesPh: 'Describa la acción tomada...',
      ackConfirm: 'Confirmar recepción',
      personnel: 'personal',
    },
    sec: {
      title: 'Operaciones de Seguridad',
      subtitle: 'Postura del establecimiento · coordinación de respuesta · integridad del perímetro',
      activeAlerts: 'Alertas Activas',
      deployed: 'Equipos Desplegados',
      lockdownZones: 'Zonas en Confinamiento',
      perimeter: 'Sectores Perimetrales',
      postureTitle: 'Control de Postura de Seguridad',
      postureSub: 'Establecer el nivel de alerta en todo el establecimiento',
      zoneMatrix: 'Matriz de Seguridad por Zona',
      responseTitle: 'Equipos de Respuesta',
      responseSub: 'Disponibilidad táctica',
      perimeterPanel: 'Integridad del Perímetro',
      alertsPanel: 'Alertas de Seguridad Activas',
      initLockdown: 'INICIAR CONFINAMIENTO',
      deploy: 'DESPLEGAR',
      recall: 'RETORNAR A BASE',
      liveEvents: 'No se registran alertas activas — establecimiento en estado nominal.',
      postureDesc1: 'Operaciones rutinarias. Patrullajes y cronogramas de movimiento estándar en vigor.',
      postureDesc2: 'Vigilancia reforzada. Patrullajes incrementados; movimiento no esencial restringido.',
      postureDesc3: 'Alerta máxima. Movimiento controlado; equipos de respuesta en posición; activación de inteligencia en curso.',
      postureDesc4: 'Incidente crítico. Protocolo de confinamiento total; todos los equipos desplegados; enlace externo activado.',
      activeLabel: 'ACTIVO',
      subLiveEvents: 'eventos de seguridad en tiempo real',
      subResponseReadiness: 'disponibilidad de respuesta',
      subMovementHalted: 'movimiento suspendido',
      subSecureTotal: 'asegurados / total',
      sectorN7: 'Línea Norte 7',
      sectorN8: 'Línea Norte 8',
      sectorE1: 'Puerta Este',
      sectorE2: 'Cerca Este',
      sectorS4: 'Patio Sur',
      sectorS5: 'Línea Sur',
      sectorW3: 'Torre Oeste',
      sectorW6: 'Cerca Oeste',
      sectorStatusSecure: 'ASEGURADO',
      sectorStatusWatch: 'VIGILANCIA',
      sectorStatusAlert: 'ALERTA',
      lockdownSelectZone: 'Seleccione la zona a confinar',
      lockdownZoneLabel: 'Zona a confinar',
      lockdownTypeLabel: 'Tipo de confinamiento',
      lockdownFull: 'Confinamiento total',
      lockdownPartial: 'Confinamiento parcial',
      lockdownPreventive: 'Confinamiento preventivo',
      lockdownDuration: 'Duración estimada',
      lockdownOpt30m: '30 minutos',
      lockdownOpt1h: '1 hora',
      lockdownOpt4h: '4 horas',
      lockdownOptIndefinite: 'Indefinido hasta nueva orden',
      lockdownReasonLabel: 'Motivo del confinamiento',
      lockdownReasonPh: 'Describa el motivo de la orden de confinamiento...',
      deployZoneLabel: 'Zona de despliegue',
      deployMissionLabel: 'Tipo de misión',
      missionPatrol: 'Patrullaje',
      missionResponse: 'Respuesta a incidente',
      missionLockdown: 'Apoyo en confinamiento',
      missionEscort: 'Escolta de reclusos',
      deployNotesLabel: 'Instrucciones especiales',
      deployNotesPh: 'Ingrese instrucciones adicionales...',
      recallReasonLabel: 'Motivo del retorno',
      recallMissionComplete: 'Misión completada',
      recallRelief: 'Relevo de turno',
      recallReassigned: 'Reasignación',
      recallNotesLabel: 'Observaciones del retorno',
      recallNotesPh: 'Ingrese observaciones...',
      teamOperators: 'operadores',
      sectorModalTitle: 'Sector',
      sectorActionLabel: 'Acción requerida',
      sectorActionPatrol: 'Solicitar patrullaje',
      sectorActionInspect: 'Inspección física',
      sectorActionLockdown: 'Activar confinamiento de sector',
      sectorActionReport: 'Registrar evento',
      sectorNotesLabel: 'Observaciones',
      sectorNotesPh: 'Describa la situación observada...',
      sectorExecute: 'Ejecutar acción',
      teamToast: 'posición avanzada',
      teamStandbyToast: 'base',
      teamStatus: {
        standby: 'EN ESPERA',
        deployed: 'DESPLEGADO',
        responding: 'EN RESPUESTA',
      },
    },
    surv: {
      title: 'Centro de Vigilancia',
      subtitle: 'Red CCTV · análisis de video mediante IA · supervisión del estado de cámaras',
      cameraGrid: 'Cuadrícula de Cámaras',
      cameraHealth: 'Estado de Cámaras',
      aiActivity: 'Actividad de Detección mediante IA',
      onlineCameras: 'Cámaras Operativas',
      offlineCameras: 'Cámaras Fuera de Servicio',
      flaggedCameras: 'Marcadas por IA',
      totalCameras: 'Total de Cámaras',
      liveCamMatrix: 'Matriz de Cámaras en Vivo',
      camInspector: 'Inspector de Cámara',
      aiDetEngine: 'Motor de Detección mediante IA',
      incCorrEngine: 'Motor de Correlación de Incidentes',
      perimSecIntel: 'Inteligencia de Seguridad Perimetral',
      thermalAnalytics: 'Análisis Térmico',
      threatEscDash: 'Panel de Escalamiento de Amenazas',
      aiPredAnalytics: 'Análisis Predictivo de IA',
      selectCamera: 'Seleccione una cámara',
      cameraId: 'Identificador de Cámara',
      online: 'OPERATIVA',
      offline: 'FUERA DE SERVICIO',
      frameRate: 'Frecuencia de Fotogramas',
      resolution: 'Resolución',
      aiFlags: 'Marcadores de IA',
      encryption: 'Cifrado',
      retention: 'Retención',
      protocol: 'Protocolo',
      networkHealth: 'Estado de la Red',
      storageUtil: 'Utilización de Almacenamiento',
      recordingActive: 'GRABACIÓN ACTIVA',
      recordingSuspended: 'GRABACIÓN SUSPENDIDA',
      continuousRec: 'Grabación continua · Respaldo en la nube habilitado',
      lastKnownState: 'Último estado conocido preservado',
      activeAiDetections: 'Detecciones Activas de IA',
      envConditions: 'Condiciones Ambientales',
      visibility: 'Visibilidad',
      lighting: 'Iluminación',
      temperature: 'Temperatura (amb.)',
      humidity: 'Humedad',
      good: 'Buena',
      adequate: 'Adecuada',
      unknown: 'Desconocida',
      allCameras: 'Todas',
      flaggedFilter: 'Marcadas',
      offlineFilter: 'Fuera de servicio',
      noMatch: 'Ninguna cámara coincide con el filtro seleccionado',
      selected: 'Seleccionada',
      aiActive: 'IA ACTIVA',
      signalLost: 'SEÑAL PERDIDA',
      liveFeed: 'TRANSMISIÓN EN VIVO',
      allFilter: 'Todos',
      criticalFilter: 'Críticos',
      highFilter: 'Altos',
      activeFilter: 'Activos',
      noDetections: 'Ninguna detección coincide con el filtro actual',
      statusBreakdown: 'Desglose por Estado',
      mostActiveZones: 'Zonas de Mayor Actividad',
      threatDist: 'Distribución de Amenazas',
      linkedEvents: 'Eventos de Detección Vinculados',
      affectedAreas: 'Áreas Afectadas',
      assocInmates: 'Reclusos Asociados',
      predictedOutcome: 'Resultado Previsto',
      recommendedAction: 'Acción Recomendada',
      currentThreatLevel: 'NIVEL DE AMENAZA ACTUAL',
      secPostureScale: 'Escala de Postura de Seguridad',
      activeEmergencies: 'Emergencias Activas',
      lockdownEffect: 'CONFINAMIENTO EN VIGOR',
      noActiveEmergencies: 'SIN EMERGENCIAS ACTIVAS',
      allProtocolsNormal: 'Todos los protocolos dentro de los parámetros normales',
      highRiskAreas: 'Áreas de Alto Riesgo (24 h)',
      behavioralAnomalies: 'Anomalías de Conducta Detectadas',
      secRecommendations: 'Recomendaciones de Seguridad',
      respTeamReadiness: 'Disponibilidad de Equipos de Respuesta',
      aiReasoning: 'Razonamiento de la IA',
      classificationKey: 'Clave de Clasificación',
      humanDetection: 'Detección de Persona',
      vehicleDetection: 'Detección de Vehículo',
      animalDetection: 'Detección de Animal',
      unknownHeat: 'Firma Térmica No Identificada',
      lastRecordedEvent: 'Último Evento Registrado',
      aiThreatAssessment: 'Evaluación de Amenaza por IA',
      fenceSensors: 'Sensores de Valla',
      thermalCameras: 'Cámaras Térmicas',
      motionSensors: 'Sensores de Movimiento',
      guardTowers: 'Torres de Guardia',
      uavSurveillance: 'Supervisión mediante UAV',
      offlineCritical: 'FUERA DE SERVICIO',
      criticalLabel: 'CRÍTICO',
      recordingChip: 'GRABANDO',
      titleFull: 'Centro de Inteligencia de Vigilancia y Seguridad',
      subtitleFull: 'Operaciones CCTV centralizadas · Motor de detección IA · Inteligencia perimetral · Correlación de incidentes',
      criticalDetections: 'Detecciones Críticas',
      openIncidents: 'Incidentes Abiertos',
      threatScore: 'Puntuación de Amenaza',
      facilityCoverage: 'cobertura total del establecimiento',
      pctOperational: '% operativo',
      maintenanceReq: 'mantenimiento requerido',
      unresolvedCritical: 'eventos críticos sin resolver',
      activeInvestigations: 'investigaciones activas',
      aiFlag: 'Marcador IA',
      recordingAllCams: 'Grabación activa en todas las cámaras operativas',
      noCamsFilter: 'Ninguna cámara coincide con el filtro actual',
      incCorrSubtitle: 'Correlación de eventos de seguridad vinculada por IA · Síntesis de patrones conductuales · Evaluación predictiva de amenazas',
      perimSubtitle: 'Sensores de valla · Cámaras térmicas · Detección de movimiento · Torres de guardia · Supervisión UAV',
      thermalSubtitle: 'Flujo de detección infrarroja · Motor de clasificación de firmas',
      threatEscSubtitle: 'Postura de seguridad en todo el establecimiento',
      aiPredSubtitle: 'Pronóstico de riesgo por zona · Detección de anomalías conductuales · Modelos de predicción de amenazas',
      lockdownZoneSuffix: 'zona bajo protocolo de confinamiento activo',
      lockdownZonesSuffix: 'zonas bajo protocolo de confinamiento activo',
      uavActive: 'activos',
      perimRiskLabel: 'RIESGO',
      perimIntrusionSingular: 'INTRUSIÓN',
      perimIntrusionPlural: 'INTRUSIONES',
      perimStatusAlert: 'ALERTA', perimStatusNormal: 'NORMAL', perimStatusCaution: 'PRECAUCIÓN',
      perimLabelN: 'Perímetro Norte', perimLabelE: 'Perímetro Este', perimLabelS: 'Perímetro Sur', perimLabelW: 'Perímetro Oeste',
      tempLabel: 'TEMP', confLabel: 'CONF', moveLabel: 'MOVIMIENTO',
      threatLabelGreen: 'NORMAL', threatLabelYellow: 'ELEVADO', threatLabelOrange: 'ALERTA ALTA', threatLabelRed: 'INCIDENTE CRÍTICO', threatLabelBlack: 'EMERGENCIA TOTAL',
      threatDescGreen: 'Establecimiento en parámetros normales. No se identifican amenazas inmediatas.',
      threatDescYellow: 'Indicadores de amenaza elevada presentes. Se requiere mayor monitoreo y densidad de patrullaje.',
      threatDescOrange: 'Amenazas de seguridad activas confirmadas. Equipos de respuesta desplegados. Personal de mando notificado.',
      threatDescRed: 'Incidente de seguridad grave en curso. Todas las unidades comprometidas. Agencias externas en alerta.',
      threatDescBlack: 'Emergencia total declarada. Postura de máxima respuesta. Agencias externas activadas.',
      detStatusDetecting: 'Detectando', detStatusVerifying: 'Verificando', detStatusConfirmed: 'Confirmado', detStatusResponding: 'Respondiendo', detStatusResolved: 'Resuelto',
      detFight: 'Detección de Riña', detWeap: 'Detección de Arma', detGang: 'Concentración de Pandilla', detFenc: 'Escalamiento de Valla', detGurd: 'Alerta de Guardia en Peligro',
      detUent: 'Entrada No Autorizada', detFire: 'Detección de Incendio', detAggr: 'Conducta Agresiva', detGath: 'Concentración No Autorizada', detDoor: 'Manipulación de Puerta de Celda',
      detMed: 'Emergencia Médica', detCtrb: 'Intercambio de Contrabando', detCrwd: 'Formación Anormal de Grupo', detRacc: 'Acceso a Área Restringida',
      detRun: 'Carrera en Zona Restringida', detSmok: 'Detección de Humo', detSobj: 'Objeto Sospechoso', detVisv: 'Violación en Control de Visitas',
      detFall: 'Detección de Caída', detNact: 'Actividad Nocturna Inusual',
      detLab0: 'Movimiento no autorizado detectado', detLab1: 'Concentración no identificada en formación', detLab2: 'Violación de zona restringida', detLab3: 'Indicador de contrabando presente', detLab4: 'Manipulación de puerta de celda',
      behav1: 'Sujeto CR-2048 — desviación conductual +2.7σ', behav2: 'Bloque B — patrón de movimiento coordinado activo', behav3: 'Valla norte — subpatrón de sondeo repetido', behav4: 'Área de carga oeste — acceso vehicular no autorizado',
      escaleTitle: 'Escalar detección de IA', escaleResponse: 'Respuesta requerida', escaleDispatch: 'Despachar equipo de respuesta', escaleVerify: 'Verificación física',
      escaleLockdown: 'Confinamiento de zona', escaleMedical: 'Respuesta médica', escaleLog: 'Solo registrar', escaleTeam: 'Equipo a despachar',
      escalePriority: 'Prioridad', escaleCritical: 'Crítica — respuesta inmediata', escaleHigh: 'Alta — en 5 minutos', escaleModerate: 'Moderada — en 15 minutos',
      escaleNotes: 'Observaciones del operador', escaleNotesPh: 'Describa la situación observada...', escaleConfirm: 'Escalar y despachar',
      camActionTitle: 'Acción de cámara', camZone: 'Zona', camStatus: 'Estado', camOperative: 'Operativa', camOffline: 'Fuera de servicio',
      camActionLabel: 'Acción requerida', camPtz: 'Ajuste de PTZ (ángulo/zoom)', camMaint: 'Solicitar mantenimiento', camReview: 'Revisar grabaciones marcadas',
      camSnapshot: 'Capturar imagen de evidencia', camReset: 'Reiniciar cámara', camActionDesc: 'Descripción de la acción', camActionDescPh: 'Describa el motivo de la acción...', camActionConfirm: 'Ejecutar acción',
    },
    inc: {
      title: 'Gestión de Incidentes',
      subtitle: 'Gestión integral del ciclo de vida desde el registro hasta el cierre del caso',
      boardTitle: 'Panel del Ciclo de Vida de Incidentes',
      boardSub: 'Gestión de casos — Haga clic en una tarjeta para acceder al expediente completo',
      logTitle: 'Registro de Incidentes',
      distTitle: 'Distribución por Tipo de Incidente',
      thId: 'ID', thType: 'Tipo', thSev: 'Gravedad', thZone: 'Zona',
      thStage: 'Etapa', thCmd: 'Comandante Responsable', thRep: 'Fecha de Reporte',
      metricOpen: 'Incidentes Abiertos',
      subNotYetClosed: 'no cerrados aún',
      metricInResponse: 'En Respuesta Activa',
      subTeamsEngaged: 'equipos comprometidos',
      metricClosed: 'Cerrados (30d)',
      subResolvedCases: 'casos resueltos',
      newTitle: 'Nuevo Reporte',
      newSubtitle: 'Registre un nuevo incidente en el sistema',
      typeLabel: 'Tipo de incidente',
      teamLabel: 'Equipo de respuesta',
      descLabel: 'Descripción del incidente',
      descPh: 'Describa el incidente con el mayor detalle posible...',
      cmdPh: 'Nombre del comandante responsable',
      confirmLog: 'Registrar incidente',
      typeAltercation: 'Altercación / Riña',
      typeContraband: 'Contrabando detectado',
      typeMedical: 'Emergencia médica',
      typeBreach: 'Violación de seguridad',
      typeEscape: 'Intento de fuga',
      typeDisturbance: 'Perturbación del orden',
      typeOther: 'Otro',
      sevCritical: 'Crítica',
      sevHigh: 'Alta',
      sevMedium: 'Media',
      sevLow: 'Baja',
      modalSummary: 'Resumen',
      modalCmdr: 'Comandante responsable',
      modalTeam: 'Equipo de respuesta',
      modalCasualties: 'Afectados',
      modalStage: 'Etapa actual',
      modalSubjects: 'Sujetos involucrados',
      modalRegistered: 'registrado hace',
      modalAgo: '',
      modalCasualtyWarn: 'afectados',
      btnAdvance: 'AVANZAR ETAPA',
      btnAssign: 'ASIGNAR COMANDANTE',
      emptyKanban: '— vacío —',
      advanceTitle: 'Avanzar etapa del incidente',
      advanceNewStage: 'Nueva etapa',
      advanceNotesLabel: 'Observaciones del avance',
      advanceNotesPh: 'Describa el progreso y las acciones tomadas...',
      advanceOfficerLabel: 'Funcionario que actualiza',
      advanceOfficerPh: 'Número de placa o nombre',
      advanceConfirm: 'Avanzar etapa',
      assignTitle: 'Asignar comandante',
      assignCmdLabel: 'Comandante responsable',
      assignCmdPh: 'Nombre y número de placa',
      assignTeamLabel: 'Equipo de respuesta',
      assignTeamPh: 'Nombre del equipo asignado',
      assignPriorityLabel: 'Prioridad de respuesta',
      assignImmediate: 'Inmediata',
      assignUrgent: 'Urgente',
      assignNormal: 'Normal',
      assignInstructLabel: 'Instrucciones al comandante',
      assignInstructPh: 'Ingrese las instrucciones correspondientes...',
      assignConfirm: 'Asignar comandante',
    },
    intel: {
      title: 'Inteligencia Penitenciaria',
      subtitle: 'Perfiles de población · análisis de asociaciones · supervisión conductual',
      riskStrat: 'Estratificación de Riesgo',
      crimeDistrib: 'Distribución por Categoría de Delito',
      watchlist: 'Lista de Vigilancia Crítica',
      popSummary: 'Resumen de Población',
      assocGraph: 'Gráfico de Asociaciones',
      profileDossier: 'Expediente del Sujeto',
      intFlags: 'Marcadores de Inteligencia',
      associates: 'Asociados Conocidos',
      thId: 'ID', thName: 'Nombre', thCrime: 'Tipo de Delito', thCustody: 'Nivel de Custodia',
      thRisk: 'Riesgo', thThreat: 'Puntuación de Amenaza', thZone: 'Zona', thStatus: 'Estado',
      thNat: 'Nacionalidad', thFlags: 'Marcadores',
      filterAll: 'Todas',
      filterExtreme: 'Extremo',
      filterHigh: 'Alto',
      filterMed: 'Med',
      filterLow: 'Bajo',
      filterAllCrimes: 'Todos los tipos de delito',
      metricTotalPop: 'Población Total',
      subActiveCustody: 'en custodia activa',
      metricViolent: 'Delincuentes Violentos',
      metricAvgThreat: 'Puntuación Promedio de Amenaza',
      sub0To100: 'compuesto 0–100',
      rosterTitle: 'Registro de Población',
      rosterOf: 'de',
      rosterSubjects: 'sujetos',
      searchIdName: 'Buscar ID / nombre…',
      moreResults: 'más — refine los filtros para reducir los resultados',
      threatLabel: 'AMENAZA',
      riskPctPop: '% de la población',
      kvCustodyLevel: 'Nivel de custodia',
      kvThreatScore: 'Puntuación de amenaza',
      kvHousing: 'Alojamiento',
      kvStatus: 'Estado',
      kvSentence: 'Condena',
      kvYears: 'años',
      kvTimeServed: 'Tiempo cumplido',
      kvLastIncident: 'Último incidente',
      kvNoRecord: 'Sin registro',
      kvDaysAgo: 'días',
      kvAge: 'Edad',
      noFlags: 'Sin marcadores activos.',
      noAssociates: 'No hay asociados registrados en la población actual.',
      knownLabel: 'conocidos',
      btnTransfer: 'TRANSFERIR',
      flagTypeLabel: 'Tipo de marcador',
      flagEscape: 'Riesgo de fuga',
      flagGang: 'Afiliación pandilleril',
      flagContraband: 'Involucrado en contrabando',
      flagViolence: 'Riesgo de violencia',
      flagInformant: 'Informante activo',
      flagProtective: 'Requiere custodia protectora',
      flagPriorityLabel: 'Prioridad de vigilancia',
      flagJustLabel: 'Justificación del marcador',
      flagJustPh: 'Describa el motivo para agregar este marcador de inteligencia...',
      transferTitle: 'Transferir recluso',
      transferCurrentZone: 'Zona actual',
      transferCurrentCell: 'Celda',
      transferDestLabel: 'Zona de destino',
      transferDestMAX: 'Ala de Máxima Seguridad',
      transferDestBLKA: 'Bloque A',
      transferDestBLKB: 'Bloque B',
      transferDestBLKC: 'Bloque C',
      transferDestMED: 'Ala Médica',
      transferDestISO: 'Unidad de Aislamiento',
      transferReasonLabel: 'Motivo de la transferencia',
      transferSecurity: 'Razones de seguridad',
      transferMedical: 'Tratamiento médico',
      transferBehavioral: 'Conducta inapropiada',
      transferProtection: 'Custodia protectora',
      transferCourt: 'Audiencia judicial',
      transferNotesLabel: 'Observaciones adicionales',
      transferNotesPh: 'Ingrese detalles sobre la transferencia...',
      transferConfirm: 'Autorizar transferencia',
      priorityCritical: 'Crítica',
      priorityHigh: 'Alta',
      priorityMedium: 'Media',
    },
    ai: {
      title: 'Análisis de Inteligencia Artificial',
      subtitle: 'Modelado predictivo de amenazas · análisis de patrones conductuales · fusión de inteligencia',
      forecastTitle: 'Pronóstico de Amenazas',
      riskStrat: 'Estratificación de Riesgo Poblacional',
      modelsTitle: 'Modelos de IA Activos',
      modelsSub: 'Estado del canal de inferencia',
      recsTitle: 'Recomendaciones Prioritarias',
      recsSub: 'Orientación operacional generada por inteligencia artificial',
      crimeProfile: 'Perfil de Amenazas por Categoría de Delito',
      crimeProfileSub: 'Puntuación promedio de amenaza por IA según categoría delictiva',
      topSignals: 'Principales Señales de Inteligencia',
      topSignalsSub: 'Indicadores con mayor nivel de confianza',
      model1Title: 'Predictor de Escalamiento de Amenazas',
      model1Desc: 'Modelo temporal basado en LSTM · ventana de pronóstico de 72h · entrenado con 5 años de datos de incidentes',
      model2Title: 'Mapeador de Patrones Conductuales',
      model2Desc: 'Red neuronal de grafos · co-ocurrencia de reclusos · correlación de patrones delictivos · análisis de desviaciones conductuales',
      model3Title: 'Calificador de Riesgo de Violencia',
      model3Desc: 'Conjunto de aumento de gradiente · características conductuales · incidentes históricos',
      model4Title: 'Detector de Flujo de Contrabando',
      model4Desc: 'Detección de anomalías · análisis de patrones de visitantes · correlación de movimientos',
      model5Title: 'Clasificador de Riesgo de Fuga',
      model5Desc: 'Bosque aleatorio · eventos perimetrales · registros de movimiento · marcadores psicológicos',
      model6Title: 'Predictor de Reincidencia',
      model6Desc: 'Riesgos proporcionales de Cox · resultados de programas de rehabilitación',
      modelStatusActive: 'activo',
      modelStatusTraining: 'entrenando',
      metricAiThreat: 'Índice de Amenaza IA',
      subCompositeScore: 'puntuación compuesta del modelo 0–100',
      metricModelsRunning: 'Modelos Activos',
      subRealTimeInference: 'inferencia en tiempo real',
      metricAvgAccuracy: 'Precisión Promedio de Modelos',
      subAcrossModels: 'en todos los modelos activos',
      trendViolenceRisk: 'Tendencia de Riesgo de Violencia',
      trendModelConf: 'Confianza del Modelo',
      trendEscapeRisk: 'Puntuación de Riesgo de Fuga',
      labelAccuracy: 'Precisión',
      labelSubjects: 'sujetos',
      labelConf: 'conf.',
      modelsActiveChip: 'MODELOS ACTIVOS',
      recExecTitle: 'Ejecutar recomendación de IA',
      recTeamLabel: 'Equipo asignado',
      recUrgencyLabel: 'Urgencia de ejecución',
      recUrgencyImmediate: 'Inmediata',
      recUrgencyPriority: 'Prioritaria (< 2 horas)',
      recUrgencyScheduled: 'Programada',
      recAuthLabel: 'Tipo de autorización',
      recAuthStandard: 'Autorización estándar',
      recAuthCommander: 'Requiere aprobación del comandante',
      recAuthDirector: 'Requiere aprobación del director',
      recNotesLabel: 'Observaciones del operador',
      recNotesPh: 'Ingrese observaciones adicionales...',
      recConfirm: 'Ejecutar recomendación',
      modelConfigTitle: 'Configurar modelo',
      modelActionLabel: 'Acción sobre el modelo',
      modelRetrain: 'Iniciar reentrenamiento',
      modelCalibrate: 'Recalibrar parámetros',
      modelPause: 'Pausar inferencia',
      modelExport: 'Exportar métricas de rendimiento',
      modelThresholdLabel: 'Umbral de confianza (%)',
      modelThresholdPh: 'Ej. 80',
      modelJustLabel: 'Justificación técnica',
      modelJustPh: 'Describa el motivo de esta acción...',
      modelApply: 'Aplicar configuración',
      minAgo: 'min atrás',
      hAgo: 'h atrás',
    },
    staff: {
      title: 'Operaciones de Personal',
      subtitle: 'Plantilla de funcionarios · gestión de turnos · control de habilitación de seguridad',
      totalPersonnel: 'Total de Funcionarios',
      onDuty: 'En Servicio',
      inResponse: 'En Respuesta Activa',
      offDuty: 'Fuera de Servicio / Con Licencia',
      roster: 'Registro de Personal',
      shiftReadiness: 'Disponibilidad por Turno',
      roleDist: 'Distribución de Funciones',
      zoneDeploy: 'Despliegue por Zona',
      thBadge: 'Número de Placa', thName: 'Nombre', thRole: 'Función', thShift: 'Turno',
      thStatus: 'Estado', thZone: 'Zona', thClearance: 'Habilitación de Seguridad',
      subAll: 'todos los turnos combinados',
      subForce: 'de la fuerza total',
      subIncident: 'despliegue por incidente',
      subUnavail: 'no disponible',
      shiftAll: 'Todos',
      searchStaff: 'Buscar nombre / placa / función…',
      shiftPrefix: 'TURNO',
      activeDeployPct: '% despliegue activo',
      addModalTitle: 'Agregar funcionario al turno',
      addModalSubtitle: 'Registre la asignación de un funcionario al turno activo',
      nameLabel: 'Nombre completo',
      namePh: 'Nombre y apellidos',
      badgeLabel: 'Número de placa',
      badgePh: 'Ej. CO-4821',
      roleLabel: 'Función',
      roleCorrections: 'Oficial de correcciones',
      roleTactical: 'Oficial táctico',
      roleMedical: 'Personal médico',
      roleAnalyst: 'Analista de inteligencia',
      roleSupervisor: 'Supervisor',
      shiftLabel: 'Turno asignado',
      zoneLabel: 'Zona de asignación',
      clearanceLabel: 'Nivel de habilitación',
      clearance1: 'Nivel 1',
      clearance2: 'Nivel 2',
      clearance3: 'Nivel 3',
      clearance4: 'Nivel 4',
      clearance5: 'Nivel 5 (máximo)',
      confirmAddStaff: 'Registrar funcionario',
      reassignTitle: 'Reasignar funcionario',
      newZoneLabel: 'Nueva zona de asignación',
      missionLabel: 'Tipo de misión',
      missionPatrol: 'Patrullaje',
      missionResponse: 'Respuesta a incidente',
      missionEscort: 'Escolta',
      missionGuard: 'Guardia fija',
      durationLabel: 'Duración de la misión',
      dur1h: '1 hora',
      dur4h: '4 horas',
      durShift: 'Turno completo',
      instrLabel: 'Instrucciones especiales',
      instrPh: 'Ingrese instrucciones adicionales...',
      confirmReassign: 'Reasignar funcionario',
      kvStatus: 'Estado',
      kvShift: 'Turno',
      kvZone: 'Zona asignada',
      kvClearance: 'Habilitación de seguridad',
      kvYearsService: 'Años de servicio',
      notAssigned: 'Sin asignar',
      clearancePrefix: 'NIVEL',
      btnReassign: 'REASIGNAR',
      btnClose: 'CERRAR',
      officersLabel: 'funcionarios',
    },
    rehab: {
      title: 'Programas de Rehabilitación',
      subtitle: 'Educación · formación vocacional · apoyo psicológico · reinserción social',
      programsActive: 'Programas en Ejecución',
      totalEnrolled: 'Total de Inscritos',
      avgCompletion: 'Tasa Promedio de Finalización',
      totalCapacity: 'Capacidad Total',
      activePrograms: 'Programas en Ejecución',
      categoryOverview: 'Resumen por Categoría',
      compliance: 'Indicadores de Cumplimiento',
      programRegister: 'Registro de Programas',
      thId: 'ID', thProgram: 'Programa', thCategory: 'Categoría', thFacilitator: 'Facilitador Responsable',
      thEnrolled: 'Inscritos', thCapacity: 'Capacidad', thUtil: 'Utilización', thCompletion: 'Tasa de Finalización',
      subAllCat: 'todas las categorías',
      subPop: 'de la población penitenciaria',
      subAcross: 'en todos los programas',
      subUtil: 'utilización',
      enrolled: 'INSCRITOS',
      avgComp: 'TASA PROMEDIO DE FINALIZACIÓN',
      catAll: 'Todas',
      catEducation: 'Educación',
      catVocational: 'Vocacional',
      catPsych: 'Psicológico',
      catSubstance: 'Sustancias',
      catReintegration: 'Reinserción',
      cardEnrollment: 'Inscritos',
      cardCompletionRate: 'Tasa de finalización',
      categoryEnrolled: 'Inscritos',
      categoryAvgComp: 'Finalización prom.',
      compliancePsychHours: 'Horas Psicológicas Obligatorias',
      complianceEducationQuota: 'Cuota de Educación',
      complianceSubstance: 'Consejería de Sustancias',
      complianceRecidivism: 'Seguimiento de Reincidencia',
      complianceAnnualReport: 'Informe Anual al Ministerio',
      complianceDueIn42d: 'VENCE EN 42 DÍAS',
      complianceCompliant: 'CUMPLE',
      complianceActive: 'ACTIVO',
      noPrograms: 'No se registran programas en esta categoría.',
      programsCount: 'programas',
      addModalSubtitle: 'Registre un nuevo programa de rehabilitación en el sistema',
      programNameLabel: 'Nombre del programa',
      programNamePh: 'Nombre descriptivo del programa',
      facilitatorPh: 'Nombre del facilitador responsable',
      capacityPh: 'Ej. 20',
      scheduleLabel: 'Horario',
      schedulePh: 'Ej. Lunes y miércoles 09:00–11:00',
      descLabel: 'Descripción del programa',
      descPh: 'Describa los objetivos y metodología del programa...',
      enrollModalAvailSlots: 'Cupos disponibles',
      enrollModalCompletionRate: 'Tasa de finalización',
      enrollInmateLabel: 'ID del recluso',
      enrollInmatePh: 'Ej. CR-1234',
      enrollMotivLabel: 'Motivación de inscripción',
      enrollVoluntary: 'Participación voluntaria',
      enrollMandatory: 'Requerimiento del tribunal',
      enrollRecommended: 'Recomendación del programa',
      enrollParole: 'Requisito de libertad condicional',
      enrollStartLabel: 'Fecha de inicio',
      enrollStartPh: 'DD/MM/AAAA',
      enrollNotesLabel: 'Observaciones de inscripción',
      enrollNotesPh: 'Ingrese observaciones relevantes...',
      kvCategory: 'Categoría',
      kvFacilitator: 'Facilitador responsable',
      kvEnrolledCapacity: 'Inscritos / Capacidad',
      kvUtilization: 'Utilización',
      kvCompletionRate: 'Tasa de finalización',
      btnClose: 'Cerrar',
      addProgramConfirm: 'Registrar programa',
    },
    twin: {
      title: 'Gemelo Digital',
      subtitle: 'Modelo esquemático en tiempo real de la planta física del CACCO',
      schematic: 'Esquema del Establecimiento — Vista General de Sectores',
      schematicSub: 'Haga clic en una zona para inspeccionarla · el color codifica la capa seleccionada',
      zoneDetail: 'Detalle de Zona',
      layers: 'Capas del Mapa',
      live: 'EN VIVO',
      layerStatus: 'Estado', layerOccupancy: 'Ocupación', layerIncidents: 'Incidentes', layerPersonnel: 'Personal',
      heatmapNone: 'Ninguno', heatmapViolence: 'Riesgo de Violencia', heatmapContraband: 'Contrabando', heatmapGang: 'Actividad Pandilleril',
      overlayGuards: 'Guardias', overlayInmates: 'Reclusos', overlayAi: 'Capa IA', overlayHeatmap: 'Mapa de Calor', overlayDoors: 'Puertas',
      guardsLabel: 'guardias', active: 'ACTIVO', lockdownActive: 'CONFINAMIENTO ACTIVO', lockdownBtn: 'CONFINAMIENTO',
      tabOverview: 'General', tabGuards: 'Guardias', tabCameras: 'Cámaras', tabSensors: 'Sensores', tabAi: 'IA', tabDoors: 'Puertas',
      clickZone: 'Haga clic en una zona para inspeccionar',
      riskLevel: 'Nivel de Riesgo', incidents24h: 'Incidentes 24h', guardsOnSite: 'Guardias en Sitio',
      facilitySummary: 'RESUMEN DEL ESTABLECIMIENTO', totalZones: 'Total de Zonas', camerasOnline: 'Cámaras Operativas',
      sensorsActive: 'Sensores Activos', sensorFaults: 'Fallas de Sensores', guardsDeployed: 'Guardias Desplegados', activeInc: 'Incidentes Activos',
      activeIncTitle: 'INCIDENTES ACTIVOS', aiPredTitle: 'PREDICCIONES DE IA',
      deployedGuardsTitle: 'GUARDIAS DESPLEGADOS', allCamerasTitle: 'TODAS LAS CÁMARAS', allSensorsTitle: 'TODOS LOS SENSORES',
      badge: 'Placa', radio: 'Radio', clearanceLevel: 'Nivel',
      aiFlags: 'Marcadores IA', recording: 'Grabación', angle: 'Ángulo', fov: 'Campo Visual',
      kvId: 'ID', battery: 'Batería', lastEvent: 'Último Evento', sensorLabel: 'SENSOR',
      dispatchGuard: 'Despachar Guardia', medicalTeam: 'Equipo Médico', tactical: 'Táctico',
      prob: 'Prob', window: 'Ventana', conf: 'Conf',
      aiThreatTitle: 'EVALUACIÓN DE AMENAZA IA', behavIntel: 'INTELIGENCIA CONDUCTUAL',
      confidence: 'Confianza', accessControl: 'CONTROL DE ACCESO', doorsLabel: 'PUERTAS',
      unlock: 'DESBLOQUEAR', lock: 'BLOQUEAR', timeline: 'LÍNEA DE TIEMPO', events: 'eventos',
      yes: 'SÍ', no: 'NO', more: 'más', zonePrefix: 'ZONA',
    },
    rpt: {
      title: 'Informes y Cumplimiento Normativo',
      subtitle: 'Informes legales · registro de auditoría · presentaciones al Ministerio de Justicia y Paz',
      scheduleTitle: 'Calendario de Informes',
      auditTitle: 'Registro de Auditoría',
      statsTitle: 'Estadísticas de Cumplimiento',
      thId: 'ID', thReport: 'Informe', thCategory: 'Categoría', thFreq: 'Frecuencia',
      thLast: 'Última Generación', thNext: 'Próximo Vencimiento', thStatus: 'Estado', thRecipient: 'Destinatario',
      thTime: 'Hora', thAction: 'Acción', thUser: 'Usuario', thRef: 'Referencia',
      exportBtn: 'EXPORTAR PDF',
      statusCurrent: 'VIGENTE',
      statusDueSoon: 'POR VENCER',
      statusOverdue: 'VENCIDO',
      metricTemplates: 'Plantillas de Informes',
      subScheduled: 'informes programados',
      metricGenerated: 'Generados (30d)',
      subTransmitted: 'transmitidos exitosamente',
      metricDueSoon: 'Por Vencer',
      subWithin3d: 'en los próximos 3 días',
      metricOverdue: 'Vencidos',
      subImmediateAction: 'acción inmediata requerida',
      reportRegistryTitle: 'Registro de Informes',
      reportRegistrySub: 'Calendario de informes legales y operacionales',
      complianceDashTitle: 'Panel de Cumplimiento',
      quickExportTitle: 'Exportación Rápida',
      auditSub: 'Registro de acciones del sistema y usuarios — clasificación: RESTRINGIDO',
      auditSeverity: 'Gravedad',
      chipOverdue: 'VENCIDOS',
      chipDueSoon: 'POR VENCER',
      idhab: 'Derechos Humanos IDHAB',
      mjsp: 'Reporte al MJSP',
      oij: 'Intercambio de Inteligencia OIJ',
      nationalAudit: 'Auditoría de Seguridad Nacional',
      inmateRights: 'Protocolo de Derechos del Recluso',
      segregation: 'Límites de Tiempo en Aislamiento',
      medicalAccess: 'Estándares de Acceso Médico',
      visitorProcessing: 'Tiempo de Procesamiento de Visitas',
      dataRetention: 'Política de Retención de Datos',
      auditLoggingLabel: 'Registro de Auditoría del Sistema',
      compCompliant: 'CUMPLE',
      compInReview: 'EN REVISIÓN',
      compScheduled: 'PROGRAMADO',
      compAttention: 'ATENCIÓN',
      compActive: 'ACTIVO',
      qePopulation: 'Instantánea de Población Actual',
      qeIncidents: 'Resumen de Incidentes Activos',
      qeAlerts: 'Registro de Alertas de Seguridad (24h)',
      qeStaff: 'Plantilla de Personal (Turno Actual)',
      qeIntelligence: 'Informe de Inteligencia',
      exportFormatLabel: 'Formato de exportación',
      exportFormatPdf: 'PDF (clasificado)',
      exportFormatXlsx: 'Excel (.xlsx)',
      exportFormatCsv: 'CSV (datos sin formato)',
      exportClassLabel: 'Nivel de clasificación',
      exportClassRestricted: 'RESTRINGIDO',
      exportClassConfidential: 'CONFIDENCIAL',
      exportClassSecret: 'SECRETO',
      exportRecipientLabel: 'Destinatario adicional',
      exportRecipientPh: 'Correo institucional o nombre del destinatario',
      exportNotesLabel: 'Notas de transmisión',
      exportNotesPh: 'Observaciones para incluir en la transmisión...',
      schedModalSubtitle: 'Configure la generación automática de un nuevo informe',
      schedTitleLabel: 'Título del informe',
      schedTitlePh: 'Nombre descriptivo del informe',
      schedCategoryLabel: 'Categoría',
      schedCatOps: 'Operaciones',
      schedCatSecurity: 'Seguridad',
      schedCatIntel: 'Inteligencia',
      schedCatRehab: 'Rehabilitación',
      schedCatCompliance: 'Cumplimiento normativo',
      schedCatGov: 'Gobernanza',
      schedFreqLabel: 'Frecuencia',
      schedFreqDaily: 'Diaria',
      schedFreqWeekly: 'Semanal',
      schedFreqMonthly: 'Mensual',
      schedFreqQuarterly: 'Trimestral',
      schedFreqAnnual: 'Anual',
      schedRecipientLabel: 'Destinatario principal',
      schedRecipientPh: 'Nombre o institución destinataria',
      viewPeriodLabel: 'Período del informe',
      viewPeriodLast: 'Última versión generada',
      viewPeriod7d: 'Últimos 7 días',
      viewPeriod30d: 'Últimos 30 días',
      viewPeriod90d: 'Últimos 90 días',
      viewNotesLabel: 'Observaciones de revisión',
      viewNotesPh: 'Registre las observaciones de esta revisión...',
      viewConfirm: 'Ver informe',
      viewTitle: 'Ver informe',
      viewLastGen: 'Última generación',
      exportRecipientDefault: 'Destinatario',
      chipRecipient: 'Destinatario',
    },
    admin: {
      title: 'Administración del Sistema',
      subtitle: 'Estado de los servicios · control de acceso · integraciones · configuración de seguridad',
      servicesTitle: 'Estado de los Servicios',
      accessTitle: 'Control de Acceso y Sesiones Activas',
      integrationsTitle: 'Integraciones con Sistemas Externos',
      servicesOnline: 'Servicios Operativos',
      avgLatency: 'Latencia Promedio',
      sessions: 'Sesiones Activas',
      mfaAlert: 'Incumplimiento de Autenticación MFA',
      thId: 'ID', thService: 'Servicio', thStatus: 'Estado', thLatency: 'Latencia',
      thUptime: 'Disponibilidad', thCategory: 'Categoría',
      thUser: 'Usuario', thRole: 'Función', thClearance: 'Habilitación de Seguridad',
      thLastLogin: 'Último Acceso', thMFA: 'MFA',
      serviceHealthTitle: 'Monitor de Estado de Servicios',
      serviceHealthSub: 'Disponibilidad y latencia de servicios en tiempo real',
      systemHealthTitle: 'Estado del Sistema',
      secConfigTitle: 'Configuración de Seguridad',
      maintenanceTitle: 'Mantenimiento y Acciones',
      subAvgUptime: 'disponibilidad promedio',
      subResponseTime: 'tiempo de respuesta',
      subAuthUsers: 'usuarios autenticados',
      subWithout2FA: 'usuarios sin 2FA',
      colHealth: 'Salud',
      statusOnline: 'OPERATIVO',
      statusDegraded: 'DEGRADADO',
      statusOffline: 'FUERA DE LÍNEA',
      mfaEnabled: 'HABILITADO',
      mfaDisabled: 'DESHABILITADO',
      chipDegraded: 'DEGRADADO',
      chipOperational: 'OPERATIVO',
      kvServicesOnline: 'Servicios Operativos',
      kvApiLatency: 'Latencia de API',
      kvSystemStatus: 'Estado del Sistema',
      kvLastBackup: 'Último Respaldo',
      kvDiskUsage: 'Uso de Disco',
      kvEncryption: 'Cifrado',
      kvMfaPolicy: 'Política MFA',
      kvSessionTimeout: 'Tiempo de Sesión',
      kvFailedLogin: 'Bloqueo por Intentos Fallidos',
      kvAuditLogging: 'Registro de Auditoría',
      kvDataClass: 'Clasificación de Datos',
      kvLastPentest: 'Última Prueba de Penetración',
      kvEnforced: 'APLICADA',
      kvPartial: 'PARCIAL',
      kvEnabled: 'HABILITADO',
      kvRestricted: 'RESTRINGIDO',
      maintRotateCodes: 'Rotar Códigos de Acceso',
      maintClearAiCache: 'Limpiar Caché de IA',
      maintExportAudit: 'Exportar Registro de Auditoría',
      maintSyncMjsp: 'Sincronizar Enlace MJSP',
      maintDiagnostics: 'Diagnóstico del Sistema',
      maintEmergencyShutdown: 'Apagado de Emergencia',
      addUserModalSubtitle: 'Registre un nuevo usuario en el sistema de control de acceso',
      nameLabel: 'Nombre completo',
      namePh: 'Nombre y apellidos del funcionario',
      roleDirector: 'Director',
      roleCommander: 'Comandante',
      roleAnalyst: 'Analista de Inteligencia',
      roleSecOfficer: 'Oficial de Seguridad',
      roleMedical: 'Personal Médico',
      roleMaintenance: 'Mantenimiento',
      clearancePrefix: 'Nivel',
      clearance5Max: 'Nivel 5 (Máximo)',
      mfaLabel: 'Autenticación MFA',
      mfaEnabledRequired: 'Habilitada (requerida)',
      mfaDisabledNotRec: 'Deshabilitada (no recomendado)',
      confirmAddUser: 'Registrar usuario',
      editUserTitle: 'Editar usuario',
      mfaStatusLabel: 'Estado MFA',
      mfaStatusEnabled: 'Habilitada',
      mfaStatusDisabled: 'Deshabilitada',
      reasonLabel: 'Motivo del cambio',
      reasonPh: 'Describa el motivo de la modificación...',
      saveChanges: 'Guardar cambios',
      maintModalSubtitle: 'Confirme los parámetros de esta operación antes de ejecutar',
      authCodeLabel: 'Código de autorización',
      authCodePh: 'Ingrese su código de autorización',
      maintJustLabel: 'Justificación operacional',
      maintJustPh: 'Describa el motivo de esta acción...',
      maintScheduleLabel: 'Programación',
      maintNow: 'Ejecutar inmediatamente',
      maintWindow: 'Durante ventana de mantenimiento',
      maintOffPeak: 'Fuera de horas pico (00:00–06:00)',
      maintConfirmPrefix: 'Ejecutar',
      accessTableSubtitle: 'Cuentas autenticadas y niveles de habilitación',
    },
    common: {
      viewDetails: 'VER DETALLES',
      execute: 'EJECUTAR RECOMENDACIÓN',
      close: 'Cerrar',
      cancel: 'Cancelar',
      confirm: 'Confirmar',
      save: 'Guardar',
      submit: 'Enviar',
      ack: 'CONFIRMAR',
      search: 'Buscar',
      active: 'ACTIVO',
      officers: 'funcionarios',
      ofPop: '% de la población',
      modelConf: 'Confianza del Modelo',
      noAlerts: 'No se registran alertas activas.',
      noPrograms: 'No se registran programas en esta categoría.',
      live: 'EN VIVO',
      occupancy: 'Ocupación',
      incidents: 'Incidentes',
      personnel: 'Personal',
      risk: 'Riesgo',
      zone: 'Zona',
      status: 'Estado',
      resumeStream: 'Reanudar transmisión',
      pauseStream: 'Pausar transmisión',
      high: 'ALTO',
      rdy: 'LISTO',
      opr: 'OPR',
      sallyPort1: 'Compuerta de Seguridad 1',
      sallyPort2: 'Compuerta de Seguridad 2',
      vehicleGate: 'Acceso Vehicular',
      droneOverwatch: 'Supervisión Aérea mediante UAV',
      secured: 'ASEGURADO',
      staged: 'EN POSICIÓN',
      activeStatus: 'ACTIVO',
      cobra: 'COBRA',
      criticalRecs: 'RECOMENDACIONES CRÍTICAS',
      highPriorityRecs: 'Recomendaciones de Alta Prioridad',
      requireImmediateReview: 'requiere revisión inmediata',
      highestSeverity: 'gravedad máxima',
      highRiskInmates: 'Reclusos de Alto Riesgo',
      riskGreaterThanHigh: 'riesgo ≥ Alto',
      modalNotes: 'Observaciones',
      modalNotesPlaceholder: 'Ingrese las observaciones correspondientes...',
      modalPriority: 'Prioridad',
      modalZone: 'Zona afectada',
      modalZonePlaceholder: 'Seleccione una zona',
      modalTeam: 'Equipo asignado',
      modalTeamPlaceholder: 'Seleccione un equipo',
      modalReason: 'Motivo',
      modalReasonPlaceholder: 'Describa el motivo de la acción...',
      modalDuration: 'Duración estimada',
      modalIncidentType: 'Tipo de incidente',
      modalDescription: 'Descripción del incidente',
      modalDescPlaceholder: 'Describa el incidente con detalle...',
      modalReporter: 'Reportado por',
      modalSeverity: 'Nivel de gravedad',
      logIncident: 'REGISTRAR INCIDENTE',
      orderLockdown: 'ORDENAR CONFINAMIENTO',
      deployTeam: 'DESPLEGAR EQUIPO',
      addPersonnel: 'ASIGNAR PERSONAL',
      escalate: 'ESCALAR',
      acknowledge: 'CONFIRMAR RECEPCIÓN',
      dismiss: 'DESCARTAR',
      exportReport: 'EXPORTAR INFORME',
      scheduleReport: 'PROGRAMAR INFORME',
      addProgram: 'AGREGAR PROGRAMA',
      enrollInmate: 'INSCRIBIR RECLUSO',
      flagInmate: 'MARCAR RECLUSO',
      generateReport: 'GENERAR INFORME',
      configService: 'CONFIGURAR SERVICIO',
      addUser: 'AGREGAR USUARIO',
      lockZone: 'BLOQUEAR ZONA',
      updateStatus: 'ACTUALIZAR ESTADO',
      viewFullProfile: 'VER PERFIL COMPLETO',
      zoneActions: 'ACCIONES DE ZONA',
    },
    tone: {
      op: { normal: 'NORMAL', elevated: 'ELEVADO', critical: 'CRÍTICO', lockdown: 'CONFINAMIENTO' },
      risk: { low: 'BAJO', medium: 'MEDIO', high: 'ALTO', extreme: 'EXTREMO' },
      threat: { info: 'INFO', low: 'BAJO', moderate: 'MODERADO', high: 'ALTO', critical: 'CRÍTICO' },
      priority: { low: 'BAJO', medium: 'MEDIO', high: 'ALTO', critical: 'CRÍTICO' },
      alertStatus: { active: 'ACTIVO', dispatched: 'DESPACHADO', contained: 'CONTENIDO', monitoring: 'EN VIGILANCIA', resolved: 'RESUELTO' },
      stage: { reported: 'REPORTADO', investigating: 'EN INVESTIGACIÓN', response: 'EN RESPUESTA', review: 'EN REVISIÓN', closed: 'CERRADO' },
      secLabel: { l1: 'NORMAL', l2: 'ELEVADO', l3: 'ALERTA MÁXIMA', l4: 'INCIDENTE CRÍTICO' },
      secCode: { l1: 'NIVEL 1', l2: 'NIVEL 2', l3: 'NIVEL 3', l4: 'NIVEL 4' },
      rag: { normal: 'NORMAL', warning: 'ADVERTENCIA', critical: 'CRÍTICO' },
    },
    kpi: {
      prevDay: 'DÍA ANTERIOR', change: 'CAMBIO', prevShift: 'TURNO ANTERIOR',
      yesterday: 'AYER', trend: 'TENDENCIA', baseline: 'LÍNEA BASE', deviation: 'DESVIACIÓN',
      nameInmates: 'Total de Reclusos', nameOccupancy: 'Ocupación del Establecimiento',
      nameAlerts: 'Alertas de Seguridad Activas', nameHighrisk: 'Reclusos de Alto Riesgo',
      namePersonnel: 'Personal en Servicio', nameThreat: 'Índice de Amenaza IA',
    },
    cards: {
      action: 'Acción', dismiss: 'Descartar', modelConf: 'Confianza del Modelo',
      src: 'FUENTE', recommended: 'Recomendación', zoneLabel: 'Zona',
      reasoning: 'Razonamiento', suggestedAction: 'Acción Sugerida',
      expectedOutcome: 'Resultado Esperado', priority: 'PRIORIDAD',
    },
  },
};

/* ─── Context ───────────────────────────────────────────────────────── */
const LanguageCtx = createContext({ lang: 'en', toggleLang: () => {} });

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const toggleLang = () => setLang((l) => (l === 'en' ? 'es' : 'en'));
  return <LanguageCtx.Provider value={{ lang, toggleLang }}>{children}</LanguageCtx.Provider>;
}

export function useLanguage() {
  return useContext(LanguageCtx);
}

/* ─── Translation hook ──────────────────────────────────────────────── */
export function useT() {
  const { lang, toggleLang } = useContext(LanguageCtx);
  const dict = DICT[lang];

  /** Dot-notation lookup: t('cc.title') → string */
  const t = (path) => {
    const parts = path.split('.');
    let node = dict;
    for (const p of parts) {
      if (node == null) return path;
      node = node[p];
    }
    return node ?? path;
  };

  return { t, lang, toggleLang };
}
